### PR TITLE
More changes to VCC

### PR DESCRIPTION
**Pull request by fgsch**
- Try to distinguish between DURATION, REAL and INT automatically.
- Explicitly mention which operands are possible when adding.

Related to #2101.

### CODE REVIEW

**Comment by nigoroll** [comment]
@fgsch it appears to me that this makes sense even with https://github.com/varnishcache/varnish-cache/wiki/vmod-polymorphism-%28for-type-conversions%29 ?

**Comment by bsdphk** [comment]
This looks OK to me.  Sorry for not saying so sooner.

**Comment by fgsch** [comment]
Merged in 6f9595e6563cf53118048bcb5d1591a6b631b84c

**Comment by hermunn** [comment]
Backport review: This is part of the big reorganization of operations in VCC, and not for 4.1.

**Pull request closed without merging**
