### PR TITLE
fix vsm_free (never incremented)

### PR DESCRIPTION
**Pull request by ehocdet**
a proposal fix for the issue: https://github.com/varnishcache/varnish-cache/issues/2187

### CODE REVIEW

**Comment by Dridi** [comment]
For some reason beyond me the build fails on travis while this patch was applied on an up to date master, so I wouldn't be bothered by that. I've seen another build of master passing.

LGTM, well spotted!

**Comment by fgsch** [comment]
I'd prefer this is done in VSM_common_free() together where g_used is decremented.

**Comment by Dridi** [comment]
Catching up with unread commits, I now believe that a29fca7 breaks pull request builds.

**Comment by fgsch** [comment]
Merged. Thanks for the PR!

**Comment by hermunn** [comment]
Backport review: Patch b8dec3334e739a backported as 1978ebff506439.

**Pull request closed without merging**
