### PR TITLE
fix client_req double count with waitlist

### PR DESCRIPTION
**Pull request by LaughingQuoll**
Fixes an issue where client_req counter does not account for waiting list re-embarks.

This issue was discovered by https://github.com/sirn

### CODE REVIEW

**Comment by Dridi** [comment]
I would prefer we revert 2e66e0b93ba6e50fa5ef499cd6a4860d0fa56134 that fails to convey the intent behind the change and then we add `client_req` coverage to existing waiting list test cases.

Also I don't consider the waiting list to be "basic" functionality, so if we really add new test cases I would prefer "^c" complex tests (b64 seems to be an exception, and doesn't look remotely basic).

**Comment by Dridi** [comment]
After some research we reached the conclusion that the original patch was correct (modulus VTC nitpicks).

Here is the sequence of relevant events:

- 2e66e0b93ba6e50fa5ef499cd6a4860d0fa56134 moves `client_req` increment to transport code
  - ESI transport doesn't go through the `R_STP_TRANSPORT` step and wasn't included anyway
- 2c59afe22ba108c7f2ab5ff75b2e30baf4ef9ec7 makes ESI go through `R_STP_TRANSPORT`
  - reverting 2e66e0b93ba6e50fa5ef499cd6a4860d0fa56134 we see ESI requests counted in `client_req` (regression)
- e9c2a488d291b3129838c411cac7312f8801ff1e adds `esi_req` for ESI sub-requests (tangentially related)

So we'll go with @LaughingQuoll's original patch except that coverage will happen in existing waiting list tests.

**Review by nigoroll — APPROVED** [review]

**Comment by hermunn** [comment]
As we are very close to a release, @Dridi will merge this manually.

**Comment by Dridi** [comment]
20d356b3d08a458c6f56117a65f9041b5f6fd405

**Pull request closed without merging**
