### PR TITLE
RFC: varnishtest: New ${repeat:<uint>:<str>} macro

### PR DESCRIPTION
**Pull request by Dridi**
When we need long strings it can become quickly unwieldy, and a
dedicated macro would help when those strings follow a repeating
pattern.

This is incomplete work in progress to be discussed.

### CODE REVIEW

**Comment by bsdphk** [comment]
I like this concept, not the naming: "repeat" sounds like a flow-control thing to me, not string production.

Maybe `${string:<uint>:<str>}` ?

or  `${string:<uint>*<str>}` ?

If we want to nail down a generic splitter-char for future ${...} use, we should pick one VAV understands:

`${string,<uint>,<string>}`

**Comment by Dridi** [comment]
The problem with VAV is that it won't allow commas in `<string>`, unless we teach it to stop splitting argument passed a maximum number.

**Comment by bsdphk** [comment]
Do we need commas in the strings ?

**Comment by bsdphk** [comment]
Actually, if we use VAV, you can:  `${string,<uint>,"this is a string with commas and spaces"}`

**Comment by Dridi** [comment]
I pushed 114062dea directly after reviewing it with @bsdphk and then reorganized macro parsing to treat the text inside the `${...}` delimiters as an argument vector.

With the current patch series (3ebcd6d11...5ada93e1c) the `${date}` macro is now registered in the main process, and the `${repeat,...}` macro is added similarly. All the error handling and documentation is missing on purpose, to see whether this is a direction we want for varnishtest macros.

The macro is still called `${repeat,...}` because I would like to sort out the underlying technical details before we look at the user interface.

**Comment by bsdphk** [comment]
Looks good.

Considering how much this improves the VTC's now I dont understand why we didnt do this much earlier.

Thanks a lot!

**Comment by Dridi** [comment]
So, regarding the name, I don't like `${string,<uint>,<str>}` but something like `${string,<action>,...}` would work for me:

- `${string,repeat,<uint>,<str>}`
- `${string,generate,<uint>}` (essentially what `-bodylen` does)
- etc

> Considering how much this improves the VTC's now I dont understand why we didnt do this much earlier.

All it took was me engaging in a pcre2 migration and getting frustrated by r1576 :)

**Comment by bsdphk** [comment]
Take it away maestro!

**Review by nigoroll — APPROVED** [review]
FTR, I only checked casually

**Comment by Dridi** [comment]
Ready for review.

**Comment by Dridi** [comment]
We should probably use the `ARGV_NOESC` flag here.

**Comment by Dridi** [comment]
bugwash: OK

**Pull request merged**
