### PR TITLE
build: Install vmod_*.vcc files

### PR DESCRIPTION
**Pull request by Dridi**
This change adds a new /usr/share/varnish/vcc (or equivalent) directory where the built-in VMOD descriptors are installed. Only vmod_debug.vcc is omitted since vmod_debug is not installed. Shipping VCC files can be useful to end users, for example, to implement VCL autocompletion in a text editor.

This change does not even begin to manage this for third-party VMODs.

### CODE REVIEW

**Comment by gquintard** [comment]
I like where this is going,

I'm happy to update `varnish-modules`, the rust ones and to open PRs to `libvmod-dynamic` (i.e. the ones I care about). Should I do that for `vmod-example`, and follow-up question: do we care about it, and/or do we have something better?

**Comment by Dridi** [comment]
> Should I do that for `vmod-example`, and follow-up question: do we care about it, and/or do we have something better?

I may look at this later and experiment with vcdk, but right now the scope is only built-in VMODs.

Since I was in the neighborhood I bundled a cleanup of VSC make rules, please yell if this should be a separate pull request.

**Comment by Dridi** [comment]
> Since I was in the neighborhood I bundled a cleanup of VSC make rules, please yell if this should be a separate pull request.

circleci is yelling in my direction that it only works on Fedora, so I will submit it independently later.

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/pull/3910

**Comment by Dridi** [comment]
bugwash: OK, I will come up with third-party support later.

**Pull request merged**
