### PR TITLE
Don't allow partial allocation of ESI memory

### PR DESCRIPTION
**Pull request by hermunn**
This pull request is a hack that fixes a problem (#1941) with allocation of ESI memory.

It is probably not going to be accepted as is, but I hope we can have a discussion on how the real fix should be.

### CODE REVIEW

**Comment by hermunn** [comment]
After working with @mbgrydeland a bit, the pull request has been updated to something less hackish. I hope this pull request can be reviewed in the normal way.

The old version is 3fbc544237ee847e59f15411a0ae61ec8aab0fdd, if anyone is interested.

**Comment by Dridi** [comment]
@hermunn I tried to simplify the test case but it doesn't seem possible.

**Comment by hermunn** [comment]
It has been applied to master and back ported to 4.1

**Comment by hermunn** [comment]
The competing pull request has been back ported, removing label.

**Pull request closed without merging**
