### PR TITLE
add a workspace for vcl events

### PR DESCRIPTION
**Pull request by nigoroll**
Supersedes #2076 
Ref: #2063

### CODE REVIEW

**Comment by bsdphk** [comment]
OK, but add a ASSERT_CLI() to vcl_event_ws()

**Comment by nigoroll** [comment]
merged manually

**Comment by nigoroll** [comment]
hello @hermunn :)
workspace:
* c4c444ca3221f8b94eb9294cbd59385a7826af68
* d0351710d38fc78dde7ef16022dc14dc19c5ba99
std.log fix and example
* edd955fcafbd1bfa6a64dee6c98d61cf12bb89d8

**Comment by hermunn** [comment]
Hello, @nigoroll :)

Backport review: This will stay a 5.0 feature.

**Pull request closed without merging**
