### PR TITLE
Fix crashes in ESI parsing and report errors

### LINKED ISSUE #1904: Panic on broken url in esi:include (Assert error in VEP_Finish(), cache/cache_esi_parse.c)
## Expected Behavior

do not crash

## Current Behavior

Varnish 4.1.2 crashes on `<esi:include src="blub.html?q="dudödeldie""/>` with

```
Apr 14 08:29:37 varnish varnishd[13443]: Error: Child (13453) Last panic at: Thu, 14 Apr 2016 08:29:37 GMT
Apr 14 08:29:37 varnish varnishd[13443]: Child (13453) Last panic at: Thu, 14 Apr 2016 08:29:37 GMT
                                         "Assert error in VEP_Finish(), cache/cache_esi_parse.c line 1083:
                                           Condition((vep->include_src) == 0) not true.
                                         thread = (cache-worker)
                                         version = varnish-4.1.2 revision 0d7404e
                                         ident = Linux,4.1.15-8-default,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
                                         Backtrace:
                                           0x435966: pan_ic+0x156
                                           0x4227bb: VEP_Finish+0x16b
                                           0x41f8a4: vfp_esi_end+0x44
                                           0x41ff58: vfp_esi_gzip_pull+0x168
                                           0x427e78: VFP_Suck+0x88
                                           0x425257: vbf_fetch_thread+0x6f7
                                           0x44b3c1: WRK_Thread+0x491
                                           0x44b82b: pool_thread+0x2b
                                           0x7f52b91bd0a4: libpthread.so.0(+0x80a4) [0x7f52b91bd0a4]
                                           0x7f52b8ef1fed: libc.so.6(clone+0x6d) [0x7f52b8ef1fed]
                                         busyobj = 0x7f528c090970 {
                                           ws = 0x7f528c090a30 {
                                             id = \"bo\",
                                             {s,f,r,e} = {0x7f528c0928e8,+1528,(nil),+57440},
                                           },
                                           refcnt = 2,
                                           retries = 0, failed = 0, state = 1,
                                           flags = {do_esi, do_gzip, is_gunzip},
                                           http_conn = 0x7f528c092ab0 {
                                             fd = 24,
                                             doclose = NULL,
                                             ws = 0x7f528c090a30,
                                             {rxbuf_b, rxbuf_e} = {0x7f528c092b60, 0x7f528c092c82},
                                             {pipeline_b, pipeline_e} = {(nil), (nil)},
                                             content_length = 134,
                                             body_status = length,
                                             first_byte_timeout = 60.000000,
                                             between_bytes_timeout = 60.000000,
                                           },
                                           filters = ESI_GZIP=0 V1F_STRAIGHT=1
```

## Steps to Reproduce (for bugs)

retrieve index.html from the zip and varnish crashes

[varnish-crash-on-broken-esi.zip](https://github.com/varnishcache/varnish-cache/files/218732/varnish-crash-on-broken-esi.zip)

## Your Environment

4.1.2 on openSuse 13.1 / openSuse Leap 42.1

### PR DESCRIPTION
**Pull request by hermunn**
Two commits in one pull request. Release memory instead of crashing on malformed ESI (fixes #1904) and then add some error logging.

### CODE REVIEW

**Comment by bsdphk** [comment]
The condition for vep_error() is wrong and much larger than necessary.

it should be:

  if (vep->state != {VEP_START VEP_BOM VEP_TESTXML VEP_NOTXML VEP_NEXTTAG}) ...

**Comment by fgsch** [comment]
Shouldn't we keep this:

```
-	AZ(vep->include_src);
-	AZ(vep->attr_vsb);
```

as a safety net and destroy the buffers where there is an error?

**Comment by bsdphk** [comment]
Weeeel, in general yes, but given how many states we can end up in, that would be a lot of repeated clean-up code, so in this case I think the answer is "no".

A more sane approach would probably be to allocate those two VSB's before we ever enter the FSM and destroy them when we leave, and only use VSB_clear() rather than alloc/free inside the FSM

**Comment by hermunn** [comment]
I will change the error condition and push -f

Is it OK to do the reorganization to use VSB_clear in a separate commit/pull request? I would like to see this in master and then in 4.1 soon, because #1904 is simply not cool.

**Comment by bsdphk** [comment]
OK for commit.

**Comment by hermunn** [comment]
Commited into master and 4.1

**Pull request closed without merging**
