### PR TITLE
respect max_restarts and fix c00028.vtc

### LINKED ISSUE #2949: max_restarts & c00028.vtc broken
c00028.vtc which was supposed to test that we limit the number of restarts, does not actually test that, rather it only tests the 503 from a single failing backend request:

```
**** v1    0.5 vsl|       1000 Begin           c sess 0 HTTP/1
**** v1    0.5 vsl|       1000 SessOpen        c 127.0.0.1 58730 a0 127.0.0.1 35505 1552821976.821147 22
**** v1    0.5 vsl|       1000 Link            c req 1001 rxreq
**** v1    0.5 vsl|       1002 Begin           b bereq 1001 fetch
**** v1    0.5 vsl|       1002 VCL_use         b vcl1
**** v1    0.5 vsl|       1002 Timestamp       b Start: 1552821976.821432 0.000000 0.000000
**** v1    0.5 vsl|       1002 BereqMethod     b GET
**** v1    0.5 vsl|       1002 BereqURL        b /
**** v1    0.5 vsl|       1002 BereqProtocol   b HTTP/1.1
**** v1    0.5 vsl|       1002 BereqHeader     b Host: 127.0.0.1
**** v1    0.5 vsl|       1002 BereqHeader     b X-Forwarded-For: 127.0.0.1
**** v1    0.5 vsl|       1002 BereqHeader     b Accept-Encoding: gzip
**** v1    0.5 vsl|       1002 BereqHeader     b X-Varnish: 1002
**** v1    0.5 vsl|       1002 VCL_call        b BACKEND_FETCH
**** v1    0.5 vsl|       1002 VCL_return      b fetch
**** v1    0.5 vsl|       1002 FetchError      b backend bad: fail errno 111 (Connection refused)
**** v1    0.5 vsl|       1002 Timestamp       b Beresp: 1552821976.821561 0.000130 0.000130
**** v1    0.5 vsl|       1002 Timestamp       b Error: 1552821976.821584 0.000152 0.000022
**** v1    0.5 vsl|       1002 BerespProtocol  b HTTP/1.1
**** v1    0.5 vsl|       1002 BerespStatus    b 503
**** v1    0.5 vsl|       1002 BerespReason    b Service Unavailable
**** v1    0.5 vsl|       1002 BerespReason    b Backend fetch failed
**** v1    0.5 vsl|       1002 BerespHeader    b Date: Sun, 17 Mar 2019 11:26:16 GMT
**** v1    0.5 vsl|       1002 BerespHeader    b Server: Varnish
**** v1    0.5 vsl|       1002 VCL_call        b BACKEND_ERROR
**** v1    0.5 vsl|       1002 BerespHeader    b Content-Type: text/html; charset=utf-8
**** v1    0.5 vsl|       1002 BerespHeader    b Retry-After: 5
**** v1    0.5 vsl|       1002 VCL_return      b deliver
**** v1    0.5 vsl|       1002 Storage         b malloc Transient
**** v1    0.5 vsl|       1002 Length          b 281
**** v1    0.5 vsl|       1002 BereqAcct       b 0 0 0 0 0 0
**** v1    0.5 vsl|       1002 End             b 
**** v1    0.5 vsl|          0 ExpKill         - EXP_Inbox flg=1e p=0x7f86824110c0 e=0.000000 f=0x0
**** v1    0.5 vsl|          0 ExpKill         - EXP_When p=0x7f86824110c0 e=1552821976.821584 f=0x1e
**** v1    0.5 vsl|          0 ExpKill         - EXP_expire p=0x7f86824110c0 e=-0.000197 f=0x0
**** v1    0.5 vsl|          0 ExpKill         - EXP_Expired x=1002 t=-0
**** v1    0.5 vsl|       1001 Begin           c req 1000 rxreq
**** v1    0.5 vsl|       1001 Timestamp       c Start: 1552821976.821205 0.000000 0.000000
**** v1    0.5 vsl|       1001 Timestamp       c Req: 1552821976.821205 0.000000 0.000000
**** v1    0.5 vsl|       1001 VCL_use         c vcl1
**** v1    0.5 vsl|       1001 ReqStart        c 127.0.0.1 58730 a0
**** v1    0.5 vsl|       1001 ReqMethod       c GET
**** v1    0.5 vsl|       1001 ReqURL          c /
**** v1    0.5 vsl|       1001 ReqProtocol     c HTTP/1.1
**** v1    0.5 vsl|       1001 ReqHeader       c Host: 127.0.0.1
**** v1    0.5 vsl|       1001 ReqHeader       c X-Forwarded-For: 127.0.0.1
**** v1    0.5 vsl|       1001 VCL_call        c RECV
**** v1    0.5 vsl|       1001 VCL_return      c hash
**** v1    0.5 vsl|       1001 VCL_call        c HASH
**** v1    0.5 vsl|       1001 VCL_return      c lookup
**** v1    0.5 vsl|       1001 VCL_call        c MISS
**** v1    0.5 vsl|       1001 VCL_return      c fetch
**** v1    0.5 vsl|       1001 Link            c bereq 1002 fetch
**** v1    0.5 vsl|       1001 Timestamp       c Fetch: 1552821976.821770 0.000565 0.000565
**** v1    0.5 vsl|       1001 RespProtocol    c HTTP/1.1
**** v1    0.5 vsl|       1001 RespStatus      c 503
**** v1    0.5 vsl|       1001 RespReason      c Backend fetch failed
**** v1    0.5 vsl|       1001 RespHeader      c Date: Sun, 17 Mar 2019 11:26:16 GMT
**** v1    0.5 vsl|       1001 RespHeader      c Server: Varnish
**** v1    0.5 vsl|       1001 RespHeader      c Content-Type: text/html; charset=utf-8
**** v1    0.5 vsl|       1001 RespHeader      c Retry-After: 5
**** v1    0.5 vsl|       1001 RespHeader      c X-Varnish: 1001
**** v1    0.5 vsl|       1001 RespHeader      c Age: 0
**** v1    0.5 vsl|       1001 RespHeader      c Via: 1.1 varnish (Varnish/6.2)
**** v1    0.5 vsl|       1001 VCL_call        c DELIVER
**** v1    0.5 vsl|       1001 VCL_return      c deliver
**** v1    0.5 vsl|       1001 Timestamp       c Process: 1552821976.821817 0.000612 0.000047
**** v1    0.5 vsl|       1001 Filters         c 
**** v1    0.5 vsl|       1001 RespHeader      c Content-Length: 281
**** v1    0.5 vsl|       1001 RespHeader      c Connection: keep-alive
**** v1    0.5 vsl|       1001 Timestamp       c Resp: 1552821976.821851 0.000645 0.000033
**** v1    0.5 vsl|       1001 ReqAcct         c 35 0 35 249 281 530
**** v1    0.5 vsl|       1001 End             c 
**** v1    0.5 vsl|       1000 SessClose       c REM_CLOSE 0.001
**** v1    0.5 vsl|       1000 End             c 
**** v1    0.5 vsl|          0 CLI             - Rd backend.list 
**** v1    0.5 vsl|          0 CLI             - Wr 200 134 Backend name   Admin      Probe    Health     Last change
vcl1.bad       healthy    0/0      healthy    Sun, 17 Mar 2019 11:26:16 GMT

***  v1    0.5 debug|Debug: Stopping Child
```

changing c00028.vtc like this exposes the issue:

```
diff --git a/bin/varnishtest/tests/c00028.vtc b/bin/varnishtest/tests/c00028.vtc
index 0399e9fdc..2c970b27d 100644
--- a/bin/varnishtest/tests/c00028.vtc
+++ b/bin/varnishtest/tests/c00028.vtc
@@ -8,6 +8,9 @@ varnish v1 -vcl {
        sub vcl_backend_fetch {
            set bereq.backend = bad;
        }
+       sub vcl_backend_error {
+           return (abandon);
+       }
        sub vcl_synth {
            return (restart);
        }
```

The problem is that `cnt_synth` transitions to `cnt_restart` which, for restarts exceeded, transitions right back to  `cnt_synth`.

I think this goes waaaay back to a0e68b31df6eeba8634e1a436cccb176e889a33f
```
diff --git a/bin/varnishtest/tests/c00028.vtc b/bin/varnishtest/tests/c00028.vtc
index 91abe455f..759f9b4a0 100644
--- a/bin/varnishtest/tests/c00028.vtc
+++ b/bin/varnishtest/tests/c00028.vtc
@@ -6,7 +6,7 @@ varnish v1 -vcl {
        }
 
        sub vcl_backend_fetch {
-           set bereq.backend = bad;
+           return (abandon);
        }
        sub vcl_error {
            return (restart);
```
The above still passes in 94e99cb511c5d50108636197cb0001d5b9b32c92

### PR DESCRIPTION
**Pull request by nigoroll**
Fixes #2949

### CODE REVIEW

**Comment by bsdphk** [comment]
The a02022 travis failure does not look spurious to me ?

**Comment by nigoroll** [comment]
@bsdphk I cannot see this locally, updated the branch to see if travis still reports it.

**Comment by Dridi** [comment]
@nigoroll, not related to your change: #2974.

**Comment by nigoroll** [comment]
@bsdphk and 2/3 travis builds are ok now, the other being also unrelated (#2975)

**Pull request merged**
