### PR TITLE
add if-range logic - backport 6.0

### PR DESCRIPTION
**Pull request by andrewwiik**
This is a direct cherry-pick so enough said.

Cherry Picked from 649ad2ba79f44fb0213331e8692361d1f6aa0daa

### CODE REVIEW

**Comment by nigoroll** [comment]
Do we want to carry maintenance of 6.0 LTS into the varnish-cache project?
I was under the impression that the VS team wanted to maintain it?

**Comment by andrewwiik** [comment]
@nigoroll Hi, I am part of VS, this is where we are maintaining it.

**Comment by nigoroll** [comment]
@andrewwiik sure, I just wonder why there are 6.0 PRs on here recently

**Comment by andrewwiik** [comment]
@nigoroll had no place else to put them :man_shrugging:

**Comment by andrewwiik** [comment]
Merge it please as I don’t permission

**Comment by rezan** [comment]
Lets have Guillaume sign off on it.

**Pull request merged**
