### PR TITLE
Allow to set (be)resp.body

### PR DESCRIPTION
**Pull request by fgsch**
This is equivalent to synthetic but using the more general set keyword.

This builds on top of #1992.

### CODE REVIEW

**Comment by fgsch** [comment]
The checks failing is expected. As the PR message says, it depends on some changes in #1992.

**Comment by bsdphk** [comment]
OK

**Comment by fgsch** [comment]
Committed.

**Comment by lkarsten** [comment]
Backport review: amends VCL syntax. Not for 4.1.

**Pull request closed without merging**
