### PR TITLE
Refactoring of the acceptor sockopt inheritance

### PR DESCRIPTION
**Pull request by Dridi**
See individual commits for all the details, and a test case in the last commit that fixes a bug that exists at least on Linux that would result in missing socket options on unix domain sockets under certain circumstances.

Before back-porting this to 6.0, we should probably back-port #3704 first.

### CODE REVIEW

**Review by nigoroll — COMMENTED** [review]
* read diffs 👍🏽 
* make check on my local linux 👍🏽 
* make check on SunOS vtester with gcc 64bit 👎🏽 
  * [02722.vtc failure](https://gist.github.com/nigoroll/cbb00e1ee679129338a04f05b86b143b)

**Review by nigoroll — COMMENTED** [review]
[updated r02722.vtc on SunOS](https://gist.github.com/nigoroll/bc22ee1cfb2f8c24492a2e6d5e640905) as of 27d680d57e1f736cc46e03bb8eb106f1d11b400e

**Comment by Dridi** [comment]
@nigoroll does this test case pass on SunOS in trunk?

```
varnishtest "HTTP/1 req body timeout on UDS"

server s0 {
        rxreqhdrs
        non_fatal
        rxreqbody
        txresp
} -dispatch

varnish v1 -arg {-a "${tmpdir}/v1.sock"}
varnish v1 -cliok "param.set debug +flush_head"
varnish v1 -cliok "param.set timeout_idle 1"
varnish v1 -vcl+backend { } -start

client c1 {
        txreq -req POST -hdr "Content-Length: 100"
        send some
        rxresp
        expect resp.status == 503
} -run
```

Adding debug logs broke 4 test cases, I will address that soon.

**Comment by nigoroll** [comment]
As discussed with @Dridi : The timeouts appear to be broken on UDS + SunOS.
It looks like not much has happened there since https://github.com/illumos/illumos-gate/commit/d3d50737e566cade9a08d73d2af95105ac7cd960 and at first sight it looks to me as if the timeouts were implemented on the socket layer.
But I need to have a closer lock, which I can't right now.

**Comment by Dridi** [comment]
When you get a chance, please share the configure output of b6fef8a4d2323b753e089a7e4beba1d5e283bcff.

**Comment by nigoroll** [comment]
@Dridi the commit you mentioned does not seem to make sense in the current context. Trying https://github.com/varnishcache/varnish-cache/commit/a1f3b064ee0b53e4f0dcce306b278d3f56bc66ed

**Comment by nigoroll** [comment]
@Dridi ok I think I understand your intention now. I am working on it and will get back.
FTR, the debug output _is_ very nice indeed. SunOS vtester:
```
$ ./varnishtest -iv tests/r02722.vtc 2>&1 | grep sockopt:
**** v1    vsl|          0 Debug           - sockopt: Setting SO_LINGER for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting SO_KEEPALIVE for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting SO_SNDTIMEO for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting SO_RCVTIMEO for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_NODELAY for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPIDLE for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPCNT for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPINTVL for TCP=:::37247
**** v1    vsl|          0 Debug           - sockopt: Setting SO_LINGER for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting SO_KEEPALIVE for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting SO_SNDTIMEO for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting SO_RCVTIMEO for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_NODELAY for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPIDLE for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPCNT for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting TCP_KEEPINTVL for TCP=0.0.0.0:61514
**** v1    vsl|          0 Debug           - sockopt: Setting SO_LINGER for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Setting SO_KEEPALIVE for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Setting SO_SNDTIMEO for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Setting SO_RCVTIMEO for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Not setting incompatible TCP_NODELAY for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Not setting incompatible TCP_KEEPIDLE for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Not setting incompatible TCP_KEEPCNT for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|          0 Debug           - sockopt: Not setting incompatible TCP_KEEPINTVL for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1000 Debug           c sockopt: Test confirmed SO_KEEPALIVE non heredity for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: SO_LINGER may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: Setting SO_KEEPALIVE for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: SO_SNDTIMEO may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: SO_RCVTIMEO may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: TCP_NODELAY may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: TCP_KEEPIDLE may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: TCP_KEEPCNT may be inherited for TCP=:::37247
**** v1    vsl|       1000 Debug           c sockopt: TCP_KEEPINTVL may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: SO_LINGER may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: Setting SO_KEEPALIVE for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: SO_SNDTIMEO may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: SO_RCVTIMEO may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: TCP_NODELAY may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: TCP_KEEPIDLE may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: TCP_KEEPCNT may be inherited for TCP=:::37247
**** v1    vsl|       1003 Debug           c sockopt: TCP_KEEPINTVL may be inherited for TCP=:::37247
**** v1    vsl|       1006 Debug           c sockopt: Test confirmed SO_KEEPALIVE non heredity for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Test confirmed SO_SNDTIMEO non heredity for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Test confirmed SO_RCVTIMEO non heredity for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not testing incompatible TCP_NODELAY for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not testing incompatible TCP_KEEPIDLE for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not testing incompatible TCP_KEEPCNT for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not testing incompatible TCP_KEEPINTVL for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: SO_LINGER may be inherited for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Setting SO_KEEPALIVE for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Setting SO_SNDTIMEO for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Setting SO_RCVTIMEO for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not setting incompatible TCP_NODELAY for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not setting incompatible TCP_KEEPIDLE for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not setting incompatible TCP_KEEPCNT for UDS=/tmp/vtc.160052.25fb627e/v1.sock
**** v1    vsl|       1006 Debug           c sockopt: Not setting incompatible TCP_KEEPINTVL for UDS=/tmp/vtc.160052.25fb627e/v1.sock
```

**Comment by nigoroll** [comment]
configure as of b6fef8a4d2323b753e089a7e4beba1d5e283bcff
```
checking for epoll_ctl... yes
checking for port_create... yes
checking for struct sockaddr.sa_len... no
checking whether SO_ACCEPTFILTER is declared... no
checking whether SO_RCVTIMEO works... yes
checking whether SO_SNDTIMEO works... yes
checking for TCP_KEEP(CNT|IDLE|INTVL) socket options... yes
checking for TCP_FASTOPEN socket option... no
...
```

**Comment by Dridi** [comment]
> checking whether SO_RCVTIMEO works... yes
> checking whether SO_SNDTIMEO works... yes

The plot thickens, can you dig deeper?

The configure script claims that those socket options work, but does b6fef8a4d2323b753e089a7e4beba1d5e283bcff also pass the VTC from https://github.com/varnishcache/varnish-cache/pull/3732#issuecomment-968899279? We might have introduced a regression for SunOS when those checks were removed. On the other hand, it could be a limitation similar to https://github.com/varnishcache/varnish-cache/pull/2980#issuecomment-486214661, where those options would work, but not the way we apply them in the acceptor code.

**Comment by nigoroll** [comment]
> can you dig deeper?

I am at it, but received several interrupts. Now context switching back to here.

**Comment by nigoroll** [comment]
Because of https://github.com/illumos/illumos-gate/commit/412cc9e98decfe9afa3ce4f414bc04fd83c9f856 I tried
```c
      memset(&msg, 0, sizeof msg);
      iov.iov_base = buffer;
      iov.iov_len = sizeof buffer;
      msg.msg_iov = &iov;
      msg.msg_iovlen = 1;
      ret = recvmsg(data_socket, &msg, 0);
```
in place of the `read()` only to notice afterwards that the respective code is probably never reached for streams:

https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/fs/sockfs/socktpi.c#L3088-L3091

**Comment by nigoroll** [comment]
As of tonight, this looks like a genuine bug/missing feature to me.
To get ahead with this PR, I suggest to merge with
```diff
diff --git a/bin/varnishtest/tests/r02722.vtc b/bin/varnishtest/tests/r02722.vtc
index ffa41d6..43f2ee2 100644
--- a/bin/varnishtest/tests/r02722.vtc
+++ b/bin/varnishtest/tests/r02722.vtc
@@ -1,5 +1,7 @@
 varnishtest "TCP vs UDS sockopt inheritance"
 
+feature cmd {test $(uname) != "SunOS"}
+
 server s0 {
         rxreqhdrs
         non_fatal
```

As the tcp part of the test works, we could split the test in two and only exclude SunOS for the UDS part, but I am fine with just excluding it completely.

**Review by nigoroll — APPROVED** [review]

**Comment by nigoroll** [comment]
FTR: https://www.illumos.org/issues/14240

**Comment by Dridi** [comment]
Force-pushed to skip SunOS in the test case for now, this can be merged once CI completes.

**Pull request merged**
