### PR TITLE
Mention in the etc/default.vcl that vcl >= 4.1; is required with UDS

### PR DESCRIPTION
**Pull request by dmatetelki**
With UDS, VCL needs to be 4.1

### CODE REVIEW

**Comment by Dridi** [comment]
Nitpick for the commit message, it's `etc/example.vcl`, otherwise LGTM.

**Comment by rezan** [comment]
Why not just make the default 4.1?

**Comment by dmatetelki** [comment]
@Dridi commit msg changed to `etc/example.vcl`.

**Comment by bsdphk** [comment]
Make it 4.1 syntax.

**Pull request closed without merging**
