### PR TITLE
Improvement for out-of-tree builds

### PR DESCRIPTION
**Pull request by Dridi**
See #2251, I haven't tested anything yet, feedback appreciated. I'll get around testing this at worst on Monday, it already includes documentation so browsing the diffs should give all context.

ping @rezan

### CODE REVIEW

**Comment by Dridi** [comment]
I have done some testing earlier than I thought I would, it works.

**Comment by rezan** [comment]
I think im still seeing the same problem. However, I would have to test how this builds into a package to be certain. Its possible this is just because I am building from source:

```
> ./configure --prefix=/usr
...
> cat varnishapi.pc
prefix=/usr
...
sysconfdir=${prefix}/etc
pkgsysconfdir=${sysconfdir}/varnish
...
```

So I cant say for sure, but it looks like we still have a prefixed `${sysconfdir}`, and in this case:

```
/usr/etc/varnish
```

**Comment by rezan** [comment]
I think this is a packaging thing, cause `varnishd` is built with this:

```
-DVARNISH_VCL_DIR='"/usr/etc/varnish:/usr/share/varnish/vcl"' 
```

So the `varnishapi.pc` is correct.

**Comment by Dridi** [comment]
It looks like your autoconf is broken, I get this:

```
$ grep -e prefix= -e sysconf varnishapi.pc
prefix=/usr
exec_prefix=${prefix}
sysconfdir=/etc
pkgsysconfdir=${sysconfdir}/varnish
```

Your varnishapi.pc is neither correct nor wrong, it is consistent with your autoconf results. What do you get with the short `configure.ac` file I showed you earlier?

https://github.com/varnishcache/varnish-cache/issues/2251#issuecomment-285796667

**Comment by rezan** [comment]
I get this:

```
> cat configure.ac
AC_INIT([foo])
AC_CONFIG_SRCDIR([configure.ac])
echo prefix: ${prefix}
echo sysconfdir: ${sysconfdir}
> autoconf
> ./configure
prefix: NONE
sysconfdir: ${prefix}/etc
> ./configure --prefix=/opt
prefix: /opt
sysconfdir: ${prefix}/etc
> ./configure --prefix=/usr
prefix: /usr
sysconfdir: ${prefix}/etc
```
I am running Ubuntu 14.

As long as the packages build with the correct information, we should be good. In the meantime, I have a proper workaround for the installation detection problem since this likely won't land in the wild for quite a few release iterations.

**Comment by Dridi** [comment]
I'm assuming you mean 14.04, I will have a look on Monday. Otherwise you still have the option to build Varnish with `--prefix=/usr --sysconfdir=/etc` (and probably `/var` needs to be fixed too). This is usually enforced during packaging, at least I can say so for Fedora.

However you are testing it wrong.

What we want to make sure is that you can install configuration files inside Varnish's `pkgsysconfdir`. So really what you want to check in this case is that your VMOD installs its config in `/usr/etc/varnish` alongside `default.vcl` and its VCL in `/usr/share/varnish/vcl`. In other words, that your VMOD project can properly inherit configuration from Varnish.

**Comment by Dridi** [comment]
Discussed offline with @rezan on Saturday, this solution works for him. Rebased against current master, most of it is polish or documentation.

**Comment by mbgrydeland** [comment]
+1 for inclusion in the release of Varnish 5.1

**Comment by hermunn** [comment]
Backport review: This great effort is varnish 5 only.

**Pull request closed without merging**
