### PR TITLE
Don't allow partial allocation of stevedore memory for ESI

### LINKED ISSUE #1941: Crash on wrong ESI code when cache is full  ( Wrong turn at cache/cache_esi_deliver.c:344 )
Varnish crashes a minute or two after getting to "full" cache, as in "the more memory we give to it the longer it works before the crash. It is hard to guess what exactly caused it as error message does not display ESI part in question (we're heavy user of ESI and trying to migrate away from v3)

Even with wrong ESI part it shouldn't crash the whole server, just 503 the request

Version 4.1.2 (from current debian testing) + softpurge vmod

     12:39:34 blade710 varnishd[17866]: Debug: Child (19345) Started
     12:39:34 blade710 varnishd[17866]: Info: Child (19345) said Child starts
     12:42:12 blade710 varnishd[17866]: Error: Child (19345) died signal=6
     12:42:12 blade710 varnishd[17866]: Error: Child (19345) Last panic at: Fri, 06 May 2016 10:42:12 GMT
     12:42:12 blade710 varnishd[17866]: "Wrong turn at cache/cache_esi_deliver.c:344:
     12:42:12 blade710 varnishd[17866]: ESI-codes: Illegal code
     12:42:12 blade710 varnishd[17866]: thread = (cache-worker)
     12:42:12 blade710 varnishd[17866]: version = varnish-4.1.2 revision 0d7404e
     12:42:12 blade710 varnishd[17866]: ident = Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
     12:42:12 blade710 varnishd[17866]: Backtrace:
     12:42:12 blade710 varnishd[17866]: 0x433815: varnishd() [0x433815]
     12:42:12 blade710 varnishd[17866]: 0x41d3d1: varnishd(VDP_ESI+0xaf1) [0x41d3d1]
     12:42:12 blade710 varnishd[17866]: 0x41aab9: varnishd(VDP_bytes+0x79) [0x41aab9]
     12:42:12 blade710 varnishd[17866]: 0x41afad: varnishd(VDP_DeliverObj+0x11d) [0x41afad]
     12:42:12 blade710 varnishd[17866]: 0x41bf03: varnishd() [0x41bf03]
     12:42:12 blade710 varnishd[17866]: 0x43600f: varnishd() [0x43600f]
     12:42:12 blade710 varnishd[17866]: 0x437596: varnishd(CNT_Request+0x1326) [0x437596]
     12:42:12 blade710 varnishd[17866]: 0x41d1ad: varnishd(VDP_ESI+0x8cd) [0x41d1ad]
     12:42:12 blade710 varnishd[17866]: 0x41aab9: varnishd(VDP_bytes+0x79) [0x41aab9]
     12:42:12 blade710 varnishd[17866]: 0x41afad: varnishd(VDP_DeliverObj+0x11d) [0x41afad]
     12:42:12 blade710 varnishd[17866]: req = 0x7f0c980f9020 {
     12:42:12 blade710 varnishd[17866]: vxid = 8487845, step = R_STP_DELIVER,
     12:42:12 blade710 varnishd[17866]: req_body = R_BODY_NONE,
     12:42:12 blade710 varnishd[17866]: restarts = 0, esi_level = 1,
     12:42:12 blade710 varnishd[17866]: sp = 0x7f0ca3a2fe20 {
     12:42:12 blade710 varnishd[17866]: fd = 176, vxid = 8487816,
     12:42:12 blade710 varnishd[17866]: client = 10.100.108.102 9796,
     12:42:12 blade710 varnishd[17866]: step = S_STP_H1PROC,
     12:42:12 blade710 varnishd[17866]: },
     12:42:12 blade710 varnishd[17866]: worker = 0x7f0caeddec80 {
     12:42:12 blade710 varnishd[17866]: stack = {0x7f0caeddf000 -> 0x7f0caedd3000},
     12:42:12 blade710 varnishd[17866]: ws = 0x7f0caeddee78 {
     12:42:12 blade710 varnishd[17866]: id = \"wrk\",
     12:42:12 blade710 varnishd[17866]: {s,f,r,e} = {0x7f0caedde420,0x7f0caedde420,(nil),+2040},
     12:42:12 blade710 varnishd[17866]: },
     12:42:12 blade710 varnishd[17866]: VCL::method = DELIVER,
     12:42:12 blade710 varnishd[17866]: VCL::return = deliver,
     12:42:12 blade710 varnishd[17866]: VCL::methods = {RECV, PASS, HASH, MISS, HIT, DELIVER},
     12:42:12 blade710 varnishd[17866]: },
     12:42:12 blade710 varnishd[17866]: ws = 0x7f0c980f9200 {
     12:42:12 blade710 varnishd[17866]: id = \"req\",
     12:42:12 blade710 varnishd[17866]: {s,f,r,e} = {0x7f0c980fb000,+1704,(nil),+57336},
     12:42:12 blade710 varnishd[17866]: },
     12:42:12 blade710 varnishd[17866]: http[req] = 0x7f0c980f9298 {
     12:42:12 blade710 varnishd[17866]: ws[req] = 0x7f0c980f9200,

### PR DESCRIPTION
**Pull request by hermunn**
When allocating ESI memory through `objallocwithnuke`, tell the sevedore
in `storage_simple.c` that getting less than all is not interesting. At
the same time, eliminate the possibility of getting less memory than
requested in `sml_trimstore`.

There is a competing pull request, #1946, that solves the same problem in a different way.

A different flag, MORE_MEM_ALLOCATED_IS_OK (similar to LESS_MEM_ALLOCED_IS_OK), signaling that getting more memory the requested is OK, has been proposed. However, I think this is artificial for the simple stevedores.

Fixes #1941

### CODE REVIEW

**Comment by fgsch** [comment]
nitpick: don't forget the () around the returned values (aka keep the style).

**Comment by hermunn** [comment]
Thanks, @fgsch, I will update it now.

**Comment by bsdphk** [comment]
I like this patch much better.

OK once you've put some newlines in the testcase so the line length becomes reasonable.

**Comment by hermunn** [comment]
I have changed the test so that the lines are not too long, and checked that it fails on current master. If I hear no objections I will push this tomorrow. In the meantime back porting to 4.1 seems to be a good idea.

**Comment by hermunn** [comment]
Commited as 11b91d198f828ef7f

**Comment by hermunn** [comment]
Backport to 4.1 is ae16ab8

**Pull request closed without merging**
