### PR TITLE
Add VMOD blob

### PR DESCRIPTION
**Pull request by slimhazard**
Add a VMOD that supports binary-to-text encodings for the BLOB data type to the standard distribution.

This is a possible solution for the issue under discussion in #2402 .

This is nearly identical to the VMOD that has been maintained at:

https://code.uplex.de/uplex-varnish/libvmod-blobcode

The main difference is that the version of the VMOD in the PR invokes VCL failure (``VRT_Fail()``) for its error handling (mostly for illegal encodings, or when there is insufficient workspace for a string or blob to be generated).

### CODE REVIEW

**Comment by slimhazard** [comment]
@bsdphk suggested naming this VMOD just "blob" (on IRC and in varnish-dev). The name can be easily changed. I prefer "blobcode", first of all because the VMOD is not "all about BLOBs", but strictly about binary-to-text encodings. Also, we already have a VMOD named "blob" in productive use, and it would be a bit of a PITA to have to go change the name where it's used:

https://code.uplex.de/uplex-varnish/libvmod-blob

VMOD blob provides these functions:
```
BOOL blob.same(BLOB, BLOB)
BOOL blob.equal(BLOB, BLOB)
INT blob.length(BLOB)
INT blob.integer(BLOB [, ENUM padding])
BLOB blob.subblob(BLOB, BYTES length [, BYTES offset])
```
With fairly obvious meanings, I think, except possibly for ``blob.integer()``, which returns the first bytes of the BLOB as an INT.

What we could do is add these functions to the present VMOD as well. Then it really is "all about BLOBs", and IMO "blob" becomes a better name.

**Comment by bsdphk** [comment]
If we add a BLOB related vmod to the project, it should be the (not too big) kitchen-sink for all stuff related to BLOBs.

For of the five functions you propose to add looks OK to me, but blob.integer() sounds too specific for my taste.  Maybe generalise it something like:

INT blob.integer(BLOB, INT offset=0, ENUM {vbe8,vbe16,vbe32, vbe64,vle8,vle16,vle32,vle64}, ...)

(Of course that forces the issue of how big an INT actually is...)

**Comment by slimhazard** [comment]
@bsdphk what about this:
```
INT blob.integer(BLOB, BYTES offset=0, ENUM {BIG, LITTLE} endian=0, BYTES bytes=0)
```
If ``endian`` is NULL, return whatever INT results from the endianness of the platform, otherwise endianness as specified.

If ``bytes`` is 0, return whatever you get from ``sizeof(INT)``, otherwise fill the INT with the number of bytes specified, but no more than ``sizeof(INT)``.

We can bikeshed about whether to silently ignore ``bytes > sizeof(INT)``, or invoke ``VRT_fail()`` in that case.

**Comment by Dridi** [comment]
> If `endian` is NULL, return whatever INT results from the endianness of the platform, otherwise endianness as specified.

What about `ENUM {HOST, BIG, LITTLE} endian = "HOST"` ?

**Comment by slimhazard** [comment]
@Dridi good idea, yes.

**Comment by slimhazard** [comment]
I'll squash all of the commits up to this point, so that the VMOD will only ever have been named 'blob'.

And will now start adding the other four functions.

**Comment by slimhazard** [comment]
Added the four functions discussed above, will squash the earlier commits this afternoon.

**Comment by bsdphk** [comment]
I tried this on FreeBSD-current and got::

      CC       libvmod_blob_la-vmod_blob.lo
    vmod_blob.c:276:22: error: cast from 'const char *' to 'void *' drops const qualifier [-Werror,-Wcast-qual]
                                                            enc, (void *) s, len,
                                                                          ^
    vmod_blob.c:281:21: error: cast from 'const char *' to 'void *' drops const qualifier [-Werror,-Wcast-qual]
                                                    free((void *) s);
                                                                  ^
    vmod_blob.c:285:17: error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
                                                    *((char *)s + len) = '\0';
                                                              ^
    vmod_blob.c:311:18: error: cast from 'const char *' to 'void *' drops const qualifier [-Werror,-Wcast-qual]
                            free((void *) b->encoding[i]);
                                          ^
    vmod_blob.c:363:21: error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
                    b->priv = (char *)p;
                                      ^
    vmod_blob.c:374:20: error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
            b->priv = (char *)p;
                              ^
    6 errors generated.
      CC       libvmod_blob_la-base64.lo
    base64.c:89:33: error: cast from 'const char *' to 'unsigned char *' drops const qualifier [-Werror,-Wcast-qual]
            const uint8_t *in = (uint8_t *)inbuf;

**Comment by slimhazard** [comment]
Squashes and fixes are in.

**Comment by nigoroll** [comment]
bugwash: rebase, squash into fewer commits, merge

**Pull request closed without merging**
