### PR TITLE
varnishadm: Only print the status in interactive mode

### LINKED ISSUE #3687: `varnishadm vcl.list  -j` produces not parsable JSON with status code on the first line
## Expected behavior

`varnishadm vcl.list  -j` should produce a valid json, but the output contains status code `200` on the first line, which is not parsable.

The status code is also added to the first line in the text output mode without -j parameter. 

## Steps to Reproduce (for bugs)
Run server:
```
docker run --rm --name varnish varnish:6.6
```

Run varnishadm
```
docker exec -it varnish varnishadm vcl.list  -j 
```

output:

```json
200
[ 2, ["vcl.list", "-j"], 1631021700.200,
  {
    "status": "active",
    "state": "auto",
    "temperature": "warm",
    "busy": 0,
    "name": "boot"
}
]
```
It affects only latest varnish version, output from `varnishadm vcl.list  -j` in older `varnish-6.5.1` returns valid json, there is no status on the first line.

## Possible Solution
Remove 200 status from json output

## Your Environment
docker, macosx

### PR DESCRIPTION
**Pull request by Dridi**
Or when the -p option is used.

Fixes #3687

### CODE REVIEW

**Comment by bsdphk** [comment]
No opinion, but sounds sensible.

**Review by nigoroll — APPROVED** [review]
sounds like a sensible fix for release

**Comment by Dridi** [comment]
Bugwash: approved for the 7.0 release. I may add VTC coverage before merging if not too complicated, otherwise test coverage will come separately.

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/commit/2ac661197a84c4ae0242e3a277a659f50dc9cec1

**Pull request merged**
