### PR TITLE
Collect bug fixes for 7.3.1

### PR DESCRIPTION
**Pull request by Dridi**
This is a list of bug fixes candidates for a 7.3.1 release:

- #3908
- #3913
- #3914

Please note that only the first one was merged, we didn't get a chance to formally approve them during the last bugwash.

### CODE REVIEW

**Comment by Dridi** [comment]
TODO: pick c83cc81fb8d3086eb5be69d8a246457c2848c0b5 too.

**Comment by daghf** [comment]
Another candidate: https://github.com/varnishcache/varnish-cache/pull/3930

**Comment by nigoroll** [comment]
I guess #3958 also

**Comment by Dridi** [comment]
And #3957 too.

**Comment by Dridi** [comment]
This is blocking the release of 7.3.1, see #3996.

**Pull request merged**
