### PR TITLE
bring back umem and add a default stevedore

### PR DESCRIPTION
**Pull request by nigoroll**
This PR brings back the umem stevedore. The first two commits are purely mechanic:
* revert of the commit which killed umem
* copy & rename of storage_malloc as the new basis
The third commit are the (pretty simple) changes required to use umem
The last commit introduces a new _default_ stevedore which defaults to umem where available and malloc otherwise and updates vtcs to make them work with both.

### CODE REVIEW

**Comment by nigoroll** [comment]
updated PR to master as of now:
* need heritage.h include
* got varnishtest -expect glob patterns, so now we can use all stevedore tests for umem also

**Comment by nigoroll** [comment]
Eating my own dog food - this code is running in production now.

**Comment by bsdphk** [comment]
Looks ok.

Could you elaborate in the docs why/how/when umem is better than malloc ?

**Comment by nigoroll** [comment]
Merged including slightly more documentation.
commits:
* ba54815bc5d5d3a6e8a5df81eb463ec899a5643f
* 8d49338c34606889bc94658b2d8e3c67f8cb3e55
* 12e6ca9d79712d28f0db96a28d27304d5278da8d
* 0fe283433ae2eb4509f3625c9dbb7e018a654293

**Comment by nigoroll** [comment]
FTR: I think we can still improve with some more custom tuning.
Currently checking `UMEM_OPTIONS=perthread_cache=0,backend=mmap`: perthread caching probably does not help much because of our mempools. mmap might help reduce fragmentation (jemalloc prefers it also).

ftr: using mdb, we can get helpful info on umem:
`mdb -o nostop -p $PID
`
```
> ::dcmds!grep umem
umalog                   - display umem transaction log and stack traces
umastat                  - umem allocator stats
umausers                 - display current medium and large users of the umem allocator
umem_cache               - print a umem cache
umem_debug               - toggle umem dcmd/walk debugging
umem_log                 - dump umem transaction log
umem_malloc_dist         - report distribution of outstanding malloc()s
umem_malloc_info         - report information about malloc()s by cache
umem_status              - Print umem status and message buffer
umem_verify              - check integrity of umem-managed memory
> ::umastat
cache                        buf     buf     buf     buf  memory     alloc alloc
name                        size  in use  in ptc   total  in use   succeed  fail
------------------------- ------ ------- ------- ------- ------- --------- -----
umem_magazine_1               16     908       -    1260     20K      1173     0
...
umem_alloc_122880         122880      18       -      18   2.11M        18     0
umem_alloc_131072         131072      11       -      11   1.38M        11     0
s0                            72   15967       -   16100   1.26M     20550     0
Transient                     72     304       -    1450    116K     12879     0
------------------------- ------ ------- ------- ------- ------- --------- -----
```

**Pull request closed without merging**
