### PR TITLE
VFP and VDPs for partial responses

### PR DESCRIPTION
**Pull request by Dridi**
Otherwise all bets are off :)

### CODE REVIEW

**Comment by Dridi** [comment]
I decided not to wait for the 4.1 patch to be ready to submit this one.

**Comment by fgsch** [comment]
Why failing? Can we ignore it instead?
I think it's pretty common that people blindly sets do_esi.

**Comment by Dridi** [comment]
> Why failing? Can we ignore it instead?

Because we can't guarantee the ESI expansion on a partial backend response, so we need to either fail or retry a new `bereq` without the range.

>  I think it's pretty common that people blindly sets do_esi.

Then maybe it shouldn't be ported to 4.1 in this case (only the testGunzip fix).

**Comment by fgsch** [comment]
> Because we can't guarantee the ESI expansion on a partial backend response, so we need to either fail or retry a new bereq without the range.

We cannot guarantee it, ever. 
`do_esi` is just an indicator - we might not find any ESI tags even for non-partial requests.

Since this can be workaround in VCL with a few lines I don't think we should go for this.
There are too many assumptions and potential fallout to make it worth it.

If anything I'd document it.

**Comment by Dridi** [comment]
> We cannot guarantee it, ever.
> do_esi is just an indicator - we might not find any ESI tags even for non-partial requests.

This case is fine, if there are no ESI tags then so be it. It's different than missing ESI tags because they are out of range or truncated.

>  There are too many assumptions and potential fallout to make it worth it.

The one case we briefly discussed is having a cacheable 206, but if it's cacheable the Range header is unset in `bereq` so we always cache the whole object. And if we were on the cacheable track and get an unattended partial response (backend misbehaving, covered by the test case) then `beresp` is marked as uncacheable and I don't think we can revert that decision.

**Comment by fgsch** [comment]
Except you could insert the Range header in v_b_f{}.

I still fail to understand why we want to add this as C code. Why not VCL?

**Comment by Dridi** [comment]
> Except you could insert the Range header in v_b_f{}.

At this point you should know what you are doing.

> I still fail to understand why we want to add this as C code. Why not VCL?

I wouldn't mind a VCL fix, so that would be a check in the built-in's v_b_r? But in this case you could still bypass the check.

**Comment by fgsch** [comment]
> At this point you should know what you are doing.

We could say the same about ESI since it's disabled by default.

Anyhow, if we add it in vcl_backend_fetch you could still bypass it, correct.

**Comment by Dridi** [comment]
I think we have finally reached mutual understanding, I hope we'll get to decide on a solution for next bugwash.

**Comment by bsdphk** [comment]
The bigger picture here is that doing any VFP/VDP processing on range responses is iffy.

Presently we only have "our own" filters (gzip/gunzip/esi) but VMOD filters are in our future, and it seems to me that filters will have to be told that a response is partial at ->init() time, and decide for themselves what to do.

This mechanism needs to ensure that you cannot bypass mandatory filtering by sending a range for the entire object with Cookie or Authentication header.

(I'm closing #2530 so we only have one issue for this)

**Comment by Dridi** [comment]
@bsdphk I failed to capture the final decision:

- The first patch disables VFPs on partial responses, so far so good?
- The second patch fails the fetch transaction for partial responses with `do_esi == true` (explicitly requested vs header-negotiated). Do we ultimately want this behavior? I think we vetoed the idea of a feature flag to control it.
- The second patch has both a `FetchError` that could be considered documentation, and actual documentation. Is that enough, or should we have more bells and whistles in `vcl(7)`?
- Do we also want to fail a `do_g[un]zip == true` on a partial backend response?
- Should I update this pull request to neuter VDPs on partial responses as well?

**Comment by rezan** [comment]
I am a little bit nervous reading some of the language here myself. The solution is to disable VFP/VDPs that we *know* about and which break in this configuration, in particular, gzip and esi. I just want to make sure... but we cannot assume all processors need to be skipped when a partial is encountered. This is the exact challenge processors bring up, how do we know what any processor actually does and when they need to be used? In particular, if I do a range of 0-99999999, I should not be able to bypass security, encoding, and storage processors.

**Comment by Dridi** [comment]
I fixed the testGunzip bug in trunk (5384df74abd77a54d03727e847e8610c7af068a8) and 4.1 (https://github.com/varnishcache/varnish-cache/commit/94a7f427c21d8bd0a91541b29141471c8cab220a) branches. I'll be happy to revisit this pull request once we reach a decision for ESI and processors in general.

**Comment by hermunn** [comment]
About back porting this: The fix by @Dridi is already in the 4.1 branch, and as far as I can see, 08bf3c8 is not necessary for backporting to 4.1. Yell if I am wrong.

**Pull request closed without merging**
