### PR TITLE
Introduce vmod-purge

### PR DESCRIPTION
**Pull request by Dridi**
This module offers a finer-grained control over purges, in the old
pre-vcl 4.0 style. For that, the signatures of VRT_purge and HSH_Purge
were updated to inform about the number of rearmed objects.

Initially suggested in #2339, it was agreed on IRC to review such a VMOD.

### CODE REVIEW

**Comment by bsdphk** [comment]
Why cant vmod_purge::soft() set ttl to non-zero values ?

**Comment by Dridi** [comment]
That is the behavior of vmod-softpurge, neuter TTL but keep other periods. In my initial proposal there was a `purge.rearm` function that could update all three of them. I can either add that function, or add a `ttl` parameter to `purge.soft` with a default value of 0. I have no strong opinion on the matter.

**Comment by bsdphk** [comment]
I think you should add the ttl=0 param, I really don't see any reason not to.

What about error handling, anything which should cause VRT_fail() ?

**Comment by Dridi** [comment]
Error handling is already in `VRT_purge`, this VMOD is merely a wrapper around it, I will update the code.

**Comment by Dridi** [comment]
Patch updated.

**Comment by fgsch** [comment]
I wonder, could we expose this in VCL, e.g. `return(purge(ttl=0s))` and expose the number of objects purged via some variable (e.g. `obj.purged`)?
We could do this for all the purge (and soft purge) variants.

**Comment by bsdphk** [comment]
Test m00031 fails about one time out of 20 on my machine, here are some of the trigger lines:

  ---- c1    1.1 EXPECT resp.status (200) == "404" failed
  ---- s1   31.3 HTTP rx timeout (fd:4 30000 ms)
  ---- c1   31.3 HTTP rx timeout (fd:18 30000 ms)
  ---- s1   31.1 HTTP rx timeout (fd:4 30000 ms)
  ---- c1   31.1 HTTP rx timeout (fd:18 30000 ms)
  ---- s1   31.0 HTTP rx timeout (fd:4 30000 ms)
  ---- c1   31.0 HTTP rx timeout (fd:18 30000 ms)

**Comment by Dridi** [comment]
Test case updated, no longer timing-sensitive on my system.

**Comment by Dridi** [comment]
OK'd during today's bugwash.

**Pull request merged**
