### PR TITLE
typedefs for real/mono time and durations

### PR DESCRIPTION
**Pull request by nigoroll**
this is far from complete, but before going through the whole tree and determining the proper type for all the uses of our doubles, @bsdphk please let me know if the simple basics are ok

### CODE REVIEW

**Comment by bsdphk** [comment]
I think we should stick to the vtim_ prefix, I don't really see a big advantage of introducing vtm_ ?

**Comment by nigoroll** [comment]
@bsdphk the motivation was to keep the VTIM_* functions with the existing signature and introduce new functions with struct-wrapping of alternative representations.
If we prefer a breaking change, keeping the VTIM prefix would be better, yes.

**Comment by bsdphk** [comment]
I think we should stick with VTIM

**Comment by Dridi** [comment]
Let's handle this cleanly this time: major soname bump if the new types diverge away from `double`.

**Comment by nigoroll** [comment]
@Dridi yes

**Comment by bsdphk** [comment]
Bugwash decision:

We'll stick with doubles, but typedef them.

Formatting with "%ju.%06ju" seems faster than %.6f, so we head that way next.

**Pull request merged**
