### PR TITLE
Include matrix of Varnish versions to VCL versions

### PR DESCRIPTION
**Pull request by xordspar0**

### CODE REVIEW

**Comment by fgsch** [comment]
Shouldn't this belong in the homepage?

**Comment by gquintard** [comment]
Most possibly, we don't want to backport that information for all the
published versions on the website

**Comment by xordspar0** [comment]
That makes sense. Where is a good place on the website for that?

**Comment by gquintard** [comment]
possibly https://varnish-cache.org/docs/index.html ?

**Comment by gquintard** [comment]
note that it possibly make sense to update the `VERSIONING` section of `man vcl` too, to explain the top VCL version allowed for one varnish version

**Comment by xordspar0** [comment]
What if we put the matrix on a new page linked from the downloads page, similar to the changelog? Or we could drop the matrix and just update the latest man page. Right now the matrix is very simple, but it could get for complicated in the future.

**Comment by hermunn** [comment]
I will make a table for the homepage (varnish-cache.org) and then close this.

**Comment by nigoroll** [comment]
-> https://github.com/varnishcache/homepage/pull/78

**Comment by xordspar0** [comment]
The reference still needs to be corrected, since it says that the current version only supports VCL 4.0. Should we remove that statement or update it just on trunk? I've updated it here: https://github.com/varnishcache/varnish-cache/pull/3078

**Pull request closed without merging**
