### PR TITLE
Cflags overhaul

### PR DESCRIPTION
**Pull request by Dridi**
⚠️ DO NOT MERGE ⚠️

I'm using this to have Travis CI test the commits I will push while I'm busy doing tests with `suncc`.

### CODE REVIEW

**Comment by Dridi** [comment]
The first part of my plan builds fine on my machine, Travis CI, and with at least one `suncc` invocation. It needs further testing, and when it's done I will nudge to get someone to try FreeBSD.

Before that will also come part 2, and hopefully I will get around the problem exposed by @nigoroll on the dev list in part 3.

**Comment by bsdphk** [comment]
Compiled & tested on FreeBSD: no problems found.

**Comment by hermunn** [comment]
Backport review: I trust that @Dridi will backport this if he feels the need.

In other words, no backport now.

**Comment by Dridi** [comment]
Nothing was merged, discussions happened outside of github and I dropped this PR.

**Comment by hermunn** [comment]
Thanks Dridi. I was thinking about the commit ca79c40, where you closed the pull request, but now I see that it is different from the content in the pull request.

**Comment by Dridi** [comment]
Probably not worth back-porting, it fixes a mix of pre-5.0 and post-5.0 warnings.

**Pull request closed without merging**
