### PR TITLE
Update changes.rst to include info on 4.1 releases

### PR DESCRIPTION
**Pull request by hermunn**
I am not sure this is correct, so I am doing this as a pull request. I have basically inserted the latest updates of doc/changes.rst from the 4.1 branch.

### CODE REVIEW

**Comment by bsdphk** [comment]
All doc commits are automatically OK with me, but I don't know if anybody else has more input ?

**Comment by fgsch** [comment]
My only nitpick is that the "[Cc]hanges since.." header / text is superfluous.

**Comment by hermunn** [comment]
Committed as afeb1a20b4. Furthermore, thanks to @fgsch, I added f4dfdb0600.

Finally I updated some links in e3ef0db30b, but we should probably update more broken links to trac in the changelog.

**Comment by hermunn** [comment]
Backport review: Nothing to backport.

**Pull request closed without merging**
