### PR TITLE
Document how to make counters in a VMOD

### PR DESCRIPTION
**Pull request by xordspar0**
The only official documentation about defining counters from a VMOD currently is the [Varnish 6.0 release notes](https://varnish-cache.org/docs/trunk/whats-new/changes-6.0.html#under-the-hood-mostly-for-developers). This patch fixes that by adding a counter section to the [VMOD reference guide](https://varnish-cache.org/docs/trunk/reference/vmod.html).

I'm using the diff from the [xkey patch that added counters](https://github.com/varnish/varnish-modules/commit/21d0c84d876315ce2377a1f1168a6aa794df5f8f) as a guide.

### CODE REVIEW

**Comment by xordspar0** [comment]
My VSC code sample is getting highlighted as Python code. Is there a way to prevent that?

**Comment by gquintard** [comment]
a quick search yields `..higlight::` and `..code-block::` (https://www.sphinx-doc.org/en/1.5/markup/code.html) but i have no idea how compatible we are with those

**Comment by xordspar0** [comment]
Thanks. `..highlight::` affects everything until the next `..highlight::` directive. I used `..code-block::` and it did the trick.

**Comment by gquintard** [comment]
I like it BUT, isn't it more of and educational addition that would fit https://github.com/varnishcache/libvmod-example better?

**Comment by xordspar0** [comment]
I'm not sure. I think there is a place for reference documentation about counters, but it's true that this is a mix of reference docs and how-to so far.

**Comment by nigoroll** [comment]
merged because I think this documentation is fit as-is. The fact that we can still add example code should not keep us from making progress.

**Comment by nigoroll** [comment]
Oh and thank you @xordspar0

**Pull request merged**
