### PR TITLE
WIP FYI B64 venc perf

### PR DESCRIPTION
**Pull request by nigoroll**
to supplement #3376, continuing there
```
**** v1   vsl|       1001 RespHeader      c t256: 7.405
**** v1   vsl|       1001 RespHeader      c t512: 14.108
**** v1   vsl|       1001 RespHeader      c t1024: 27.988
```

### CODE REVIEW

**Comment by nigoroll** [comment]
the build is failing because I overlooked to change the b64 handling in the vtc, but for the purpose of #3376 this is not relevant. The purpose of this PR is only to share the code used for the test.

**Comment by bsdphk** [comment]
Just because any kind of benchmark with n=1 irks me, I reran these benchmarks with `-n 100 -j 4`:

        x _blob_256
        + _venc_vsb_256
        * _venc_inline_256
            N           Min           Max        Median           Avg        Stddev
        x 100         2.492        13.925         9.648       7.80285     2.8187722
        + 100         6.558        49.333       26.9545      28.52949     9.8402985
        Difference at 95.0% confidence
                20.7266 +/- 2.00627
                265.629% +/- 35.7935%
                (Student's t, pooled s = 7.23799)
        * 100         5.285        39.108       22.5045      24.59876     8.5625633
        Difference at 95.0% confidence
                16.7959 +/- 1.76686
                215.254% +/- 30.9977%
                (Student's t, pooled s = 6.37428)


        x _blob_1024
        + _venc_vsb_1024
        * _venc_inline_1024
            N           Min           Max        Median           Avg        Stddev
        x 100         8.297        36.786        14.798       16.0126     7.4824722
        + 100        24.971        72.963        27.211      42.88031     19.279838
        Difference at 95.0% confidence
                26.8677 +/- 4.05346
                167.791% +/- 34.0363%
                (Student's t, pooled s = 14.6236)
        * 100          20.3        76.301        60.238      54.26403     18.652575
        Difference at 95.0% confidence
                38.2514 +/- 3.93909
                238.883% +/- 38.5307%
                (Student's t, pooled s = 14.211)

The `_inline` is a hacked up inline-able version of `VSB_putc()` just for this benchmark.

As I suspected the overhead of actually calling VSB, as opposed to what VSB actually does leans heavily on the later, so at least this question is not a convincing argument for an inline version of VSB.

**Comment by nigoroll** [comment]
FTR, `vtc.benchmark` runs n=1000 by default https://github.com/varnishcache/varnish-cache/pull/3381/commits/903611f1a3e48d0ba1843efd205941fd2af4992e#diff-b8275285396563fc686ca3a648f23c81R172

**Comment by bsdphk** [comment]
I've decided we leave vmod_blob alone for now.

**Pull request closed without merging**
