### PR TITLE
Don't panic if we reembark with a request body

### PR DESCRIPTION
**Pull request by daghf**
This moves the body status decision to h2_end_headers, to make sure that
it is only done once per request.

We also move the Cookie header concatenation to h2_end_headers, to avoid
stepping on any changes that may have taken place in VCL.

Fixes: #2305

### CODE REVIEW

**Comment by daghf** [comment]
Added another commit to address the second issue brought up in #2305.

If the END_STREAM flag is set  we will with this treat it as a PROTOCOL_ERROR if a content-length header is spotted.

**Comment by bsdphk** [comment]
Re second commit:  Should we not make an exception for C-L: 0 ?

**Comment by daghf** [comment]
@bsdphk agree - I'll update with a fix

**Comment by daghf** [comment]
@bsdphk Updated now - I changed the `http_GetHdr(..)` into an `http_GetContentLength(..)`:

```
--- a/bin/varnishd/http2/cache_http2_proto.c
+++ b/bin/varnishd/http2/cache_http2_proto.c
@@ -531,7 +531,7 @@ h2_end_headers(struct worker *wrk, struct h2_sess *h2,
                        req->req_body_status = REQ_BODY_WITH_LEN;
        } else {
                assert (req->req_body_status == REQ_BODY_NONE);
-               if (http_GetHdr(req->http, H_Content_Length, &b))
+               if (http_GetContentLength(req->http) > 0)
                        return (H2CE_PROTOCOL_ERROR); //rfc7540,l,1838,1840
        }
 ```

**Comment by bsdphk** [comment]
OK

**Pull request merged**
