### PR TITLE
Madvise dontdump

### PR DESCRIPTION
**Pull request by lkarsten**
I fumbled the #2080 PR somehow, so here is an updated one that cleans up after itself.

### CODE REVIEW

**Comment by nigoroll** [comment]
Re: #2080
* can't see the page alignment addressed
* I still think this should be a debug switch, not just enabled hardcoded

**Comment by bsdphk** [comment]
Please add similar stanza for *BSD's MAP_NOCORE, while you ponder the madness of why they are different.  Then commit.

**Comment by lkarsten** [comment]
Update: We've had production traffic on this in Varnish Plus, with less than optimal results.

Martin spent a while staring a crash due to excessive number of memory maps, and believe this is the reason. In hindsight this (i think) makes sense; somewhere the state of dump/nodump has to be stored.

It would be a nice functionality to have for the malloc stevedore, but unless someone wants to go digging for a way to avoid the memory map issue we should leave it unmerged.

Closing without merge.

**Comment by nigoroll** [comment]
Thank you @lkarsten and @mbgrydeland for the reality check! Actually this is consistent with concerns I had (see also #2080).

**Comment by delthas** [comment]
Additional reason why this might not be possible: if those objects are free()d but the original memory pool isn't returned to the system, you'll have unused pages held by the memory allocator with MADV_DODUMP, that will be dumped. Same issue as here: https://stackoverflow.com/questions/64847205/core-dump-size-is-increased-after-freeing-memory-that-was-excluded-from-the-core#comment114650525_64847205

Seems like we'll never be able to create reasonably-sized memory dumps on systems with large malloc storage backends.

**Pull request closed without merging**
