### PR TITLE
ESI workspace assert - backport

### PR DESCRIPTION
**Pull request by andrewwiik**
Commits:
54af42d4c328089625a59eb063e75d5c72125852
0f3af407f65ac4bc6d446c61fb3e3b50747194cd
d1bd80e83a88a0caaaf7e5021472e23d244a8ac6

(This is a redo of #3284)

### CODE REVIEW

**Comment by andrewwiik** [comment]
@rezan can you label, approve, and merge this.

**Comment by rezan** [comment]
This conflicts with https://github.com/varnishcache/varnish-cache/pull/3324

**Comment by rezan** [comment]
This conflicts with https://github.com/varnishcache/varnish-cache/pull/3325

**Comment by rezan** [comment]
@andrewwiik ping, this needs to be un-conflicted. Then I can test and merge.

**Comment by rezan** [comment]
https://github.com/varnishcache/varnish-cache/pull/3339

**Pull request closed without merging**
