### PR TITLE
implements memory barrier for arm

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by nigoroll** [comment]
Shouldn't all three macros be used?

**Comment by Dridi** [comment]
My skeptical self needs more than a one-liner diff and a one-liner commit log :)

> Shouldn't all three macros be used?

Something we could do after the `#ifdef` dance is:

```c
#ifndef VWMB
#  define VWMB()	VMB()
#endif
#ifndef VRMB
#  define VRMB()	VMB()
#endif
```

This way we don't have to worry about how fine-grained our barriers are for each architecture or system.

**Comment by nigoroll** [comment]
@Dridi that is what I had in mind

**Comment by bsdphk** [comment]
@mbgrydeland 

Martin, do you know if we can ditch vmb.h and use <stdatomic.h> instead ?

**Comment by mbgrydeland** [comment]
I assume you ask me wrt to the shmlog-stuff using the V*MB()-macros. Those should be expressable as release-consume fence operations. Would probably be a good time to have a critical view on some of that usage. I'm not at all certain that we are consistent.

I am a bit concerned with the availability of stdatomic.h though. That is C11, and if I did the research  correct it appeared in GCC 4.9. Centos 7 is a platform that is still very much relevant for us, and GCC in Centos7 it is at GCC 4.8.

I'm sure that these issues can be solved through some ifdef'ery, but we should be prepared to accept that we may not find stdatomic.h universally available on all platforms.

**Comment by nigoroll** [comment]
>  we may not find stdatomic.h universally available on all platforms.

Yes. It is not available on our smartos vtest box yet, but I have not updated that for long.

**Comment by bsdphk** [comment]
See PR in #3363

**Comment by bsdphk** [comment]
#3363 moved us onto <stdatomic.h> for "new" platforms, including ARM.

**Pull request closed without merging**
