### PR TITLE
set a custom storage_hint for cache_req_body

### PR DESCRIPTION
**Pull request by ehocdet**
Cache big req body should not eat the Transient storage.
The use case is to store the body on a dedicated sfile when CL is big.

### CODE REVIEW

**Comment by bsdphk** [comment]
This looks like a good idea.

I'm getting to dislike the "hint" thing for storage more and more.  I think we should bite the bullet and teach VCC about storage spaces, and make a VCL_ type for them.  5.0 is a good time for that.

**Comment by nigoroll** [comment]
@ehocdet we got the VCL_STEVEDORE type in the meantime, would you like to adjust your PR to that? I'll close this PR for now, please re-open or create a new one.

**Comment by ehocdet** [comment]
@nigoroll  ok i will check that.

**Comment by hermunn** [comment]
Backport review: This pull has been replaced by #2108 and #2111. Nothing to backport.

**Pull request closed without merging**
