### PR TITLE
Interactive varnishstat help screen

### PR DESCRIPTION
**Pull request by Dridi**
One of the items from #2990, It is currently lacking test coverage.

Otherwise, it works (on my machine).

### CODE REVIEW

**Comment by Dridi** [comment]
Test coverage added, now it works on my machine and in varnishtest (on my machine).

**Comment by Dridi** [comment]
This PR will close #2990 if merged, I took care of the initial verbosity too.

**Comment by bsdphk** [comment]
No comments.

**Comment by nigoroll** [comment]
@Dridi can you please merge https://github.com/nigoroll/varnish-cache/tree/varnishstat-help ?
We need two adjustments to changes someone from Paris made recently ;)

**Comment by Dridi** [comment]
Rebased against master.

**Comment by Dridi** [comment]
Considering that I have @nigoroll's explicit approval and @bsdphk did not veto, I'm planning to use my "own" vote to merge this as soon as the code freeze is lifted.

That should give plenty of time for objections from other interested parties, if any.

**Pull request merged**
