### PR TITLE
Roll back the fix for #1206, so that client delivery solely decides if resp.status==304

### PR DESCRIPTION
**Pull request by slimhazard**
whether to set client response 304, regardless of the pass state of
the backend fetch. That is, set resp.status 304 (at ESI level 0)
iff req.http.{INM,IMS} matches resp.http.{ETag,Last-Modified}.

This means that the client will get a 304 response in the pass
cases where the backend sets ETag or Last-Modified to match INM/IMS,
but nevertheless declines to set beresp.status to 304. This behavior
is consistent for the three kinds of pass: "ordinary" pass (return(pass)
in vcl_recv), beresp.uncacheable ("hit-for-miss"), and the recently
revived hit-for-pass (return(pass(DURATION)) in vcl_backend_response).

r02042.vtc shows how to restore the behavior from #1206, by unsetting
INM/IMS in vcl_pass (for ordinary pass) or vcl_miss (for hit-for-miss).

### CODE REVIEW

**Comment by slimhazard** [comment]
This and PR #2235 are two possible fixes for issue #2042 -- we'll need one or the other of them, not both. See #2042 for details.

**Comment by fgsch** [comment]
That's a hell of a large test. Do we really need it to be that large?
Also, can you normalize whitespace in the test?

**Comment by slimhazard** [comment]
Yeah, you're right on both counts. The test is in part to clarify some things, and since the docs will want to have some VCL snippets, this way we know what works. But not all of it has to live in Varnish forever. And sorry about the whitespace.

**Comment by slimhazard** [comment]
We decided for this one in today's bugwash, fixed in  6b518c4.

**Comment by hermunn** [comment]
Backport review: For 4.1 the patch goes through, but the test case for #2042 does not compile, and it is not immediately clear to me how to change the test case. Because of this I will not backport it now, but I will leave the backport review tag for now.

**Comment by hermunn** [comment]
We will keep this out of 4.1 - keeping consistent behavior is more important than the feature this PR implements.

**Pull request closed without merging**
