### PR TITLE
Collapsing cookies correctly

### LINKED ISSUE #2291: Collect cookie-headers when running h2
When running h2 its common that the client sends multiple cookie headers to increase compression.

According to https://tools.ietf.org/html/rfc7540#section-8.1.2.5 a h2 -> h1 proxy should concat multiple cookies into one delimited by "0x3B 0x20"

## Expected Behavior
That I only see one single req.http.cookie header delimited by "; "

## Current Behavior
Varnish sends multiple Cookie-headers to the backend.

## Possible Solution
1. Collect cookie-headers default when running h2.
2. Get std.collect( to take a delimiter option. 
     `std.collect(req.http.cookie, "; ");`

### PR DESCRIPTION
**Pull request by Dridi**
Fixes #2291 and #2292 and improves a bit further.

@simonvik, please try this out too.

### CODE REVIEW

**Comment by bsdphk** [comment]
I'm OK with this, subject to it actually working.

API-wise it should be safe for 5.1.2.

Not clear if the Collect should happen in C or (builtin-)VCL, nor if there is any reason to make it H2 only ?

Doc in .vcc file says 'comma' but it really is 'comma + space'

**Comment by Dridi** [comment]
I will comment tomorrow, because I won't be present during next bugwash to discuss this.

**Comment by Dridi** [comment]
> I'm OK with this, subject to it actually working.

I had a look at the failures on Travis, usual tests flakiness (same h2 tests that sometimes fail on vtest too these days). I restarted the failing job and it passed the second time.

> API-wise it should be safe for 5.1.2.

See e5097a4, it is. I also added a placeholder in `vrt.h` for the release.

> Not clear if the Collect should happen in C or (builtin-)VCL

Definitely in C, because this is a transport-specific matter. I also added a comment (see 9c261d1) for RFC coverage. An alternative to doing it before `vcl_recv` (this PR) could be after `vcl_backend_fetch`.

> nor if there is any reason to make it H2 only ?

I didn't want to do it in H1 because it isn't supposed to happen. Cookies can easily be expensive and collapsing them can eat much workspace. There's no reason for a Varnish user to see this behavior in the wild, unless they have a legacy client. In that case they can use `std.collect`.

> Doc in .vcc file says 'comma' but it really is 'comma + space'

Indeed, as I said to @simonvik on IRC I thought that `std.collect` already had a `", "` separator, but that was a side effect of keeping leading blanks. So when I fixed that in ad9623d you can notice that the only affected test case was the one created in this PR. That's why I forgot this detail in the docs: it didn't break existing behavior. Will push a docfix too.

**Comment by Dridi** [comment]
> I'm OK with this, subject to it actually working.

I had a look at the failures on Travis, usual tests flakiness (same h2 tests that sometimes fail on vtest too these days). I restarted the failing job and it passed the second time.

> API-wise it should be safe for 5.1.2.

See e5097a4, it is. I also added a placeholder in `vrt.h` for the release.

> Not clear if the Collect should happen in C or (builtin-)VCL

Definitely in C, because this is a transport-specific matter. I also added a comment (see 9c261d1) for RFC coverage. An alternative to doing it before `vcl_recv` (this PR) could be after `vcl_backend_fetch`.

> nor if there is any reason to make it H2 only ?

I didn't want to do it in H1 because it isn't supposed to happen. Cookies can easily be expensive and collapsing them can eat much workspace. There's no reason for a Varnish user to see this behavior in the wild, unless they have a legacy client. In that case they can use `std.collect`.

> Doc in .vcc file says 'comma' but it really is 'comma + space'

Indeed, as I said to @simonvik on IRC I thought that `std.collect` already had a `", "` separator, but that was a side effect of keeping leading blanks. So when I fixed that in ad9623d you can notice that the only affected test case was the one created in this PR. That's why I forgot this detail in the docs: it didn't break existing behavior. Will push a docfix too.

**Comment by simonvik** [comment]
Seems to solve my issue, running in production for a while now.

**Comment by bsdphk** [comment]
Some comments:

Strictly speacking we cannot just update copyright year for adding a single C prototype, that is a trivial change relative to the rest.

Also: Don't use <ctype.h> for HTTP headers, use "vct.h"

Also: Let http_CollectHdrSep() do the NUl/NULL check on sep.

**Comment by Dridi** [comment]
Done:

* 8dc398a
* 9ff704f
* 2708889
* c81bb85
* 01f991e
* 090653e

**Comment by bsdphk** [comment]
I'm still not convinced that we should only collect cookies for H2 ?

Also, don't bump the API version until 5.1.2 is out.  Vmods will have to wait a cycle before calling this.

**Comment by Dridi** [comment]
Merged without the VRT bump:

* 84e98d8
* 99efebb
* eadcc45
* 58b2d30
* d26a828
* 5087989

**Comment by hermunn** [comment]
Backport review: There is no need to collapse cookies in 4.1, so we don't.

**Pull request closed without merging**
