### PR TITLE
[LTS Backport] Catch up VTCP fixes

### PR DESCRIPTION
**Pull request by stevendore**
Original ticket: #3415
Original PR: #3430
Continuation of #3579

### CODE REVIEW

**Comment by rezan** [comment]
This needs to run thru the tests. I think we can skip the ASAN tests for this and just focus on load and stability.

**Comment by Dridi** [comment]
> I think we can skip the ASAN tests for this and just focus on load and stability.

I added this commit precisely not to lose the ability to use ASAN on the stable branch with what we have in tree (suppressions and all) so I would recommend to check that sanitizer builds didn't break on the stable branch as far as the test suite goes as a minimal baseline.

**Comment by rezan** [comment]
ok, we can rerun the ASAN tests

**Comment by stevendore** [comment]
ASAN test and plain load test are running.

**Review by rezan — APPROVED** [review]
Tests came back clean, but be advised we only test on Linux.

**Pull request merged**
