### PR TITLE
Vsl query booleans

### PR DESCRIPTION
**Pull request by nigoroll**
I'm suggesting this after having failed to train my grey matter to think `and` when wanting to express `&&` in vsl

### CODE REVIEW

**Comment by nigoroll** [comment]
I overlooked a local test failure - broke the existing boolean verbs

**Comment by Dridi** [comment]
I'm not convinced by the POLA-ness of this change, but having both should be OK.

**Comment by nigoroll** [comment]
bugwash: @mbgrydeland prefers to reserve these operators for later use (possibly and/or operators with slightly different semantics)

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.

**Pull request closed without merging**
