### PR TITLE
+= operator

### PR DESCRIPTION
**Pull request by dmatetelki**
DRAFT! Do not merge

Initial stab at #3079

When "s += line", happens, the generated code is rewritten as "s = line + s"

The tokenlist is not modified.

### CODE REVIEW

**Comment by nigoroll** [comment]
without looking at details, my expectation would be that a simpler solution should be possible

**Comment by bsdphk** [comment]
I think we should aim at getting to a point where WS optimizations are possible, and that means pushing the actuall append into VRT land.

In other words, I would prefer we add a `VRT_AppendHdr(VRT_CTX, VCL_HEADER, VCL_STRANDS)` function, and let that do the actual string composition.

**Comment by nigoroll** [comment]
> In other words, I would prefer we add a `VRT_AppendHdr(VRT_CTX, VCL_HEADER, VCL_STRANDS)` function, and let that do the actual string composition.

How would this avoid the additional copies? Would it check if the existing header was the last thing on the workspace?

**Comment by dmatetelki** [comment]
closing in favor of https://github.com/varnishcache/varnish-cache/pull/3116

**Pull request closed without merging**
