### PR TITLE
Introduce vtim_real and vtim_mono typedefs to clarify semantics

### PR DESCRIPTION
**Pull request by nigoroll**
This is to prepare for more work to
- use mono time instead of real time
- use a real base timestamp offset with mono time where required/useful

Also relevant for fixing #1874 

from the commit msg:

Durations remain of type double

Exceptions:
- functions agnostic to real/mono time
- vrt interface

### CODE REVIEW

**Comment by nigoroll** [comment]
BTW, this has ZERO function changes

**Comment by fgsch** [comment]
Might be worth adding vtim.h to common.h and remove it from other places.
I think this is cleaner, specially now that cache.h and mgt.h need it.

**Comment by nigoroll** [comment]
@fgsch ok, also travis reported a typedef redefinition, so I had produced a duplicate include
fixing now

**Comment by nigoroll** [comment]
as discussed with @bsdphk we want to go the longer route and fix the typing issue for real. Will open a new PR when ready.

**Comment by lkarsten** [comment]
Nothing commited, nothing to backport.

**Pull request closed without merging**
