### PR TITLE
[LTS Backport] HTTP1 minimal response assert

### PR DESCRIPTION
**Pull request by stevendore**
Original ticket: https://github.com/varnishcache/varnish-cache/issues/3415
Original PR: https://github.com/varnishcache/varnish-cache/pull/3430

### CODE REVIEW

**Review by rezan — COMMENTED** [review]
This needs extra testing, but I think our current load test and traffic sim should cover it.

**Comment by Dridi** [comment]
Summoning @mbgrydeland, we probably don´t want most of those changes, at least some are debatable.

**Comment by rezan** [comment]
This passed our load test and traffic simulation. Will wait to see if anyone has further comments.

**Comment by rezan** [comment]
Going to merge this tomorrow. I think we have a few other PRs where there were disagreements on implementation details, but I think its best to just backport them as is unless there is something unsound with the code.

**Review by rezan — APPROVED** [review]
Good to go

**Comment by rezan** [comment]
81aa74ccbd6682a69a08141e7058b001b7c47efe
e5391c5f7fd1b727ee5c1358f9adf2f1a55ac0ad

**Comment by Dridi** [comment]
b8b29be5ba4180ff7afb2a332aeb2fa543fd06dc

**Pull request merged**
