### PR TITLE
std.ip: Always provide some form of fallback

### PR DESCRIPTION
**Pull request by Dridi**
Otherwise valid code can panic on workspace exhaustion:

    std.ip(req.http.X-Real-IP, std.ip(req.http.X-Client-IP, client.ip))

If the nested std.ip() call runs out of workspace, it will return a null
ip instead of the fallback, and since the outer std.ip() call is getting
a fallback argument, it will panic upon checking the suckaddr sanity.

Refs a3b26d0ba7dd8763a4e34d9e18d92fc24f1c291c

### CODE REVIEW

**Comment by bsdphk** [comment]
I think this should be a `VRT_fail()` ?

**Comment by Dridi** [comment]
We could.

In the scenario I got where the nested `std.ip()` call runs out of workspace, the nested call `VRT_fail`s but the parent call panics upon getting a null IP.

**Review by nigoroll — APPROVED** [review]

**Comment by Dridi** [comment]
I will submit a patch for the 6.0 branch too.

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/pull/3748

**Pull request merged**
