### PR TITLE
circleci: Trade Ubuntu xenial for focal

### PR DESCRIPTION
**Pull request by Dridi**
And bionic inherits the "oldest Ubuntu" 32bit setting.

---

Submitted as a pull request only to exercise CI first.

### CODE REVIEW

**Comment by Dridi** [comment]
@gquintard HALP

**Comment by gquintard** [comment]
Looks good to me, any worry?

**Comment by Dridi** [comment]
I'm not seeing a distcheck_ubuntu_focal job in this pull request.

**Comment by gquintard** [comment]
You haven't created such a job :-) the focal job you have added is a packaging one, that will run nightly

**Comment by Dridi** [comment]
That should be good enough, thanks!

**Pull request merged**
