### PR TITLE
64bit integer precision for VCL_INT / VCL_BYTES

### PR DESCRIPTION
**Pull request by nigoroll**
Ref #2926

### CODE REVIEW

**Comment by slimhazard** [comment]
Getting way pedantic here: do we have any rules to the effect that a VCL INT is only decimal, or could it be octal or hex, by the usual lexical rules? (Leading '0' for octal, prefix '0x' for hex.)

I seem to recall that the lexer for numbers in a VSL query string might interpret them as octal or hex (but I didn't find the code that I thought I remember, maybe if I search a little longer). Of course VCL INTs and integers in a log query are not the same thing, but users might well expect the same rules.

Back when I went a little overboard re-implementing VSL queries in another language, I did [this here](https://code.uplex.de/uplex-varnish/varnishapi/blob/master/pkg/log/bytesconv.go) to parse numbers in a query as float, decimal, octal or hex, because I was sure that Varnish VSLQ does the same thing (test vectors [here](https://code.uplex.de/uplex-varnish/varnishapi/blob/master/pkg/log/bytesconv_test.go)).

**Comment by nigoroll** [comment]
@slimhazard `VNUMpfx()` does decimal https://github.com/varnishcache/varnish-cache/blob/master/lib/libvarnish/vnum.c#L72
At this point I would (only) want to replace it. Other bases should be easy to add and we could do that later.

On a related topic, I am working on adding support for scaled integers.

**Comment by nigoroll** [comment]
I have pushed additional commits to complement (but not yet test & document) VCL_BYTES parsing as integers. I would appreciate reviews by all, but particularly @bsdphk : Any feedback if the general direction is accepted would be very helpful to reduce wasted efforts.
Patches are not yet polished!
Comments:

* *way out of precision hell & tests*  d5ceb7f 

as can be seen from the removed code, I had actually made an attempt to get to decent precision near UINT64_MAX, but rounding errors with the removed code are so massive that I think we should just refuse the combination of a large unit in combination with a high number of digits.

* relative bytes (*5% of x*) were supported by `vnum.c`, but not used anywhere, so I have removed this feature.

**Comment by nigoroll** [comment]
waiting for @bsdphk feedback please. General feedback is sufficient, no detailed review required

**Comment by nigoroll** [comment]
I've now addressed the integer precision thing by optimizing the int << shift / scale arithmatic

**Comment by nigoroll** [comment]
I have polished the commits a bit more for separation of additions, syntactic change and semantic change

**Comment by nigoroll** [comment]
Changed std.integer also

**Comment by nigoroll** [comment]
conclusion from discussion with @bsdphk and @Dridi : wait for [structured headers](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-14) to settle

**Comment by Dridi** [comment]
With the march towards RFC8941 number ranges, is this still relevant?

**Comment by nigoroll** [comment]
While I am not entirely happy with the choice to reduce our integer precision to below 64bit, it has always been @bsdphk s argument that if SF settles, varnish should be adjusted accordingly - and this is a relevant argument after all.
So I surrender this PR.

**Pull request closed without merging**
