### PR TITLE
Remove temporary directory iff called with -C

### LINKED ISSUE #1869: Temporary directories used by -C are left around
`varnishd -b:1234 -C` will not remove the temporary directory, potentially leaving multiple **vcl_.CflagTest.&lt;pid&gt;** directories around.

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #1869.

### CODE REVIEW

**Comment by bsdphk** [comment]
Shouldn't we able to assert the rmdir() then ?

**Comment by fgsch** [comment]
Sure. PR updated.

**Comment by bsdphk** [comment]
OK for commit.

**Comment by lkarsten** [comment]
Handled in #1869.

**Pull request closed without merging**
