### PR TITLE
feature: Transit buffer

### PR DESCRIPTION
**Pull request by fwsGonzo**
This PR implements the transit buffer feature (previously called pass buffering).

### CODE REVIEW

**Comment by nigoroll** [comment]
this PR has an infinite complexity/description ratio

**Comment by fwsGonzo** [comment]
Feel free to give some input on what the defaults should be. Zero bytes transit buffer has to be allowed, because that disables the feature.

**Comment by fwsGonzo** [comment]
I rebased against latest and added a commit message. The message is not very long right now so if there's anything you would like  me to add there, I will be happy to do that.

**Comment by Dridi** [comment]
I force-pushed a split of the transit buffer patch into 4 commits. Doing so, I tried to polish the commit log, C code and test cases. I couldn't make c112 fail reliably with transit buffer disabled (it passes reliably when enabled) so I didn't keep it.

**Comment by nigoroll** [comment]
powwow: @nigoroll to propose an implementation without the timeout

**Comment by nigoroll** [comment]
rebased onto master here https://github.com/nigoroll/varnish-cache/tree/transit_buffering
now working on the proposed chane

**Comment by nigoroll** [comment]
`tests/c00110.vtc` (formally `tests/c0009.vtc`)  is not reliable on the rebased but otherwise onmodified a2ca25fc658afe0d6d69d010ff5bfb0b647887a0
```
$ ./varnishtest -in 1000 -j50 tests/c00110.vtc 
...
---- v1    Not true: VBE.vcl1.s1.conn (1) == 0 (0)
```

@fwsGonzo / @Dridi could you look into this?
My plan on this ticket was to implement my proposed change (which I still think should be safe, sound and simple), but this issue seems non trivial and is blocking any other progress...

**Comment by fwsGonzo** [comment]
I am running on an X1 Carbon laptop the same test with lower parallelism, but I am unable to reproduce. Should add that I am extending varnishtest to support my CMake build system, but other than that everything is the same. I rebased using your transit_buffering branch.

**Comment by nigoroll** [comment]
@fwsGonzo can we just have the branch for this PR updated without unrelated commits please?

**Comment by fwsGonzo** [comment]
You can push to it if you want!

**Comment by anthosz** [comment]
Dear all,

Do we have an estimation when it will be merged and for which version?

Really interesting feature that can save memory and optimize stability 😁

**Comment by fwsGonzo** [comment]
@anthosz You can probably just build this PR from source and use it as-is. As long as @nigoroll did not break anything with his improvements, it should be fine. This feature has been running in production in the enterprise version of Varnish for a long time now.

**Comment by anthosz** [comment]
> @anthosz You can probably just build this PR from source and use it as-is. As long as @nigoroll did not break anything with his improvements, it should be fine. This feature has been running in production in the enterprise version of Varnish for a long time now.

Thank you but it's strange that it's not merged in this case 🤔

**Comment by nigoroll** [comment]
Pushed in the context of this PR: caf49d8b42b97c3599e01f2e503d24991a1a0bcf

**Pull request merged**
