### PR TITLE
Ban to vmod and error msg

### PR DESCRIPTION
**Pull request by nigoroll**
* move the ban function to vmod std
* return the error string or the empty string if no error

### CODE REVIEW

**Comment by fgsch** [comment]
If we ran out of workspace we won't log anything at all. This is different to the existing behaviour.

**Comment by nigoroll** [comment]
> If we ran out of workspace we won't log anything at all. This is different to the existing behaviour.
Not for those cases where `err` is a fixed string, but otherwise yes.
I don't think this is relevant, but if you think it is, we can buy this by complicating the code a bit

**Comment by fgsch** [comment]
That's one concern. The other is that by moving the code to std people won't be able to ban from other VMODs. 
I reckon we should leave the code in core and either add a new argument or split the function into 2.
I believe this is how we have done it in the past (e.g. rollback).

**Comment by nigoroll** [comment]
@fgsch, good point. vmods should be able to issue bans.
So should we keep `VRT_ban_string` in core with a changed signature (returning the error or NULL) and still move the VCL `ban()` function to _std_ in order to get rid of the extra vcc code?

**Comment by lkarsten** [comment]
Why do you want this to be in a vmod and not in core?

**Comment by fgsch** [comment]
@lkarsten: 

@nigoroll mentioned it on irc. The idea is to be able to obtain the error if the ban failed for whatever reason and communicate it back to the requester via synth.

**Comment by lkarsten** [comment]
I see. I would hope that we could keep VCL compatibility through such a change.

**Comment by fgsch** [comment]
I'd prefer not to break backward compatibility either for point releases.
Maybe have them back-to-back until the next major release?

**Comment by nigoroll** [comment]
@lkarsten @fgsch thank you for your feedback. I'm back now after a one-week break, hope to get back to this soon-ish

**Comment by nigoroll** [comment]
I'll close this one and open a new PR when ready

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.

**Comment by nigoroll** [comment]
continued in #3486

**Pull request closed without merging**
