### PR TITLE
Improve error when calling vrt_do_string with ""

### PR DESCRIPTION
**Pull request by fgsch**
Should address #1856 to some extent.

### CODE REVIEW

**Comment by bsdphk** [comment]
We shoudln't mark overflow in that case, should we ?

**Comment by fgsch** [comment]
I followed what we do if we try to set .status to an invalid code. 
I'm not convinced overflow is the way to go but I'm not super keen on ignoring the error.
What are the alternatives?

**Comment by fgsch** [comment]
As discussed on IRC phk would prefer if this adds the 50x abort mechanism in VRT context instead of piggybacking on the overflow.

**Comment by fgsch** [comment]
This will be replaced by a different implementation eventually. 

Closing.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.

**Pull request closed without merging**
