### PR TITLE
Add a configure switch to skip backtrace() calls

### PR DESCRIPTION
**Pull request by gquintard**
musl libc doesn't doesn't support backtrace/backtrace_symbols, but there
are stubs for them, so varnish will compile/link/run, but will crash
once they are called.

There are solutions to keep the features but they all involve extra libraries,
so I went for the big hammer first: just not calling
backtrace/backtrace_symbols.

more context: https://redmine.alpinelinux.org/issues/5079

### CODE REVIEW

**Comment by fgsch** [comment]
Grepping musl I can't find any stubs. 

Is there a way to detect if this build is using musl instead of adding a configure option though?

**Comment by gquintard** [comment]
that would be too easy: https://www.openwall.com/lists/musl/2013/02/08/9

the other option is to compile and run a test program during configure, it just didn't seem worth the hassle.

**Comment by fgsch** [comment]
I'd prefer that option then. 

Users of musl will get a working binary without having to know about a special configure parameter.

**Comment by gquintard** [comment]
I feared you might say that :-) Should I leave the parameter in to force the behavior?

**Comment by fgsch** [comment]
My personal opinion is no but your call.

**Comment by gquintard** [comment]
I think we are good with that second commit. I ended up keeping the command-line switch for easier testing

**Comment by bsdphk** [comment]
Question:  Does the stub functions crash/abort/exit or does our code not expect their dummy return values and crash/abort/exit ?

**Comment by gquintard** [comment]
They just crash

**Comment by bsdphk** [comment]
I just cloned MUSL source, and cannot find the stubs, where are they ?

The word 'backtrace' only ever appears in a comment in an awk script ?

**Comment by gquintard** [comment]
can't find the page about stubs back, but it appears I was wrong anyway. I opened a ticket on the libexec project used by alpine (https://github.com/mikroskeem/libexecinfo/issues/2), but was redirected to the musl team (https://www.openwall.com/lists/musl/2019/08/22/2)

I'm out of my depth here, but from what I understand, the libexecinfo available on alpine won't work anyway, so we can either use something else (https://github.com/freebsd/freebsd/tree/master/contrib/libexecinfo ?) or just unplug the feature conditionally (what is done in this PR).

**Comment by mikroskeem** [comment]
FYI Alpine is not related with my repository at all, they pull [libexecinfo from FreeBSD Freshports](https://git.alpinelinux.org/aports/tree/main/libexecinfo/APKBUILD).

**Comment by gquintard** [comment]
@mikroskeem, apologies, "libexecinfo for musl libc" got me confused.

**Comment by rofl0r** [comment]
> the other option is to compile and run a test program during configure

no, you shouldn't run a test program ever as this breaks cross-compilation. it will be sufficient to compile a .c file containing `#include <execinfo.h>` and if it compiles, it means the functionality is there. for more details see https://sabotage-linux.github.io/blog/5/ which explains in great detail how to properly configure-check for things that are cross-compilation compatible. whether it then crashes at runtime is Not Your Problem, as in that case the implementation (in this case an external libexecinfo) is buggy and needs a fix. also having an explicit configure switch like --disable-execinfo is a good idea so it can be turned off even if execinfo.h is detected.

**Comment by gquintard** [comment]
@rofl0r, fair enough, I can change that to only compile.

I dug a little more and I think I found the crux of the issue: the quick-and-dirty port of libexecinfo that is used in [alpine](https://git.alpinelinux.org/aports/tree/main/libexecinfo/APKBUILD) (pulled from freeBSD) uses `__builtin_return_address()` and `__builtin_frame_address()` which are basically just dangerous. From `man gcc`:

```
       -Wframe-address
           Warn when the __builtin_frame_address or __builtin_return_address is called with an argument greater than 0.  Such calls may return indeterminate values or crash the program.  The warning is included in -Wall.
```

the question is now would: what do we do?

- be content with a way to just disable backtraces
- consider that it's alpine's job to come up with a decent and mandatory `libexecinfo` implementation
- implement #3052 and go with `libunwind` instead, but accept losing the filename in the backtrace

The first and last options sound good enough for me. `libundwind` has the advantage of being pretty much the same on all platforms, but there is some information loss.

**Comment by gquintard** [comment]
handled in #3052

**Pull request closed without merging**
