### PR TITLE
Switch to globbing on the whole string

### LINKED ISSUE #2022: varnishstat -1 -f field inclusion glob doesn't allow VBE backend fields
## Expected Behavior
When trying to view individual statistics about a backend I would expect to be able to run 
`sudo varnishstat -1 -f "VBE.boot.default.happy"` OR `sudo varnishstat -1 -f VBE\.boot\.default\.happy ` and get the correct results.

This works with similar commands:
`sudo varnishstat -1  -f LCK.wstat.locks
LCK.wstat.locks          55950         0.32 Lock Operations
`

## Current Behavior
When running these commands now I get the error `-f: Wrong number of elements`.

## Steps to Reproduce (for bugs)
Run varnish with multiple backends, attempt to query individual backend fields with varnishstat -f  command.

## Context
I am trying to configure zabbix autodiscovery and monitoring of individual backends. The ability to run this for each backend would make it easier.

## Your Environment

* Version used: `varnishstat (varnish-4.1.2 revision 0d7404e)` and `varnishstat (varnish-4.0.3 revision b8c4a34)`
* Operating System and version: Tested on both RHEL 7.1 and Archlinux

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #2022

### CODE REVIEW

**Comment by bsdphk** [comment]
Looks OK to me.

It's about time we start to think about regression testing the utils

**Comment by fgsch** [comment]
Yes, I've been thinking about this as well. 

Should we start using uppercase letters?

**Comment by fgsch** [comment]
Merged in 8bb7e90f9adf8502cd0be382cb546a28f9e24390.

**Comment by hermunn** [comment]
Backport review: The workaround is "good enough" for 4.1, so this will not be backported.

**Pull request closed without merging**
