### PR TITLE
Introduce optional numeric arg to std.ip

### PR DESCRIPTION
**Pull request by gquintard**

### CODE REVIEW

**Comment by Dridi** [comment]
In order to maintain current behavior, `BOOL numeric = 1` should actually be `BOOL numeric = 0`. Thank @daghf for this pointing out, I got this one backwards...

**Comment by gquintard** [comment]
duh, I knew that. Thanks for the keen eye. Re-running the test before amending

**Comment by bsdphk** [comment]
If your resolver library needs this, it is badly broken.

A well-formed numerical address should never cause the resolver library to do network traffic...

**Comment by Dridi** [comment]
@bsdphk on the other hand if we get said IP addresses from an untrusted third party, we may want to prevent spurious lookups.

**Comment by fgsch** [comment]
I wonder if we should make numeric the default and add another function that resolves.

**Comment by bsdphk** [comment]
Bugwash consensus:

Make the new optional arg "resolve = true" and don't change default.

**Pull request merged**
