### PR TITLE
Conditional requests when there is no body

### PR DESCRIPTION
**Pull request by rezan**
This addresses https://github.com/varnishcache/varnish-cache/issues/3341. It reverts the change previously made to disable conditional requests when there is no body. I also add a regression VTC to cover this case.

### CODE REVIEW

**Comment by rezan** [comment]
What would be the case for keeping this?

**Comment by bsdphk** [comment]
That it has worked fine for a long time for, as far as we know, N-1 users.

**Comment by nigoroll** [comment]
re @rezan cases for keeping it:
* see https://github.com/varnishcache/varnish-cache/issues/3341#issuecomment-640615695
* when we already know the object is empty, a 304 has no benefit in terms of no body being sent

**Comment by rezan** [comment]
So regarding the comment that corrupted empty response can come in, that's not possible. You need either a content length or a chunked response. Both of these conditions make an empty response invalid for modern HTTP.

And right, the goal here was to allow the backend to make the decision for a 304. I understand that Varnish sees no benefit for 304 vs 200 as both will insert a fresh object into cache.

Feel free to close this.

**Comment by bsdphk** [comment]
@rezan I'm going to pull out my veto, because having you and slink haggle about this is counter productive.

This can go in on if controlled by a default-off feature flag.

**Comment by rezan** [comment]
No problem, I will close this.

**Comment by nigoroll** [comment]
@rezan if the empty body (in the form as a correct http response) is an error in itself, the current logic helps.

**Pull request closed without merging**
