### PR TITLE
varnishstatdiff: New utility to compare metrics

### PR DESCRIPTION
**Pull request by Dridi**
As I was comparing the output of two varnishstat executions that were
captured after a fresh start of varnishd followed by the workloads to
compare, I realized diff(1) was giving me a hard time, and git-diff(1)
barely improved the situation.

Looking for generic command line utilities to compare metrics I wasn't
able to find anything. So instead I came up with the output format I
thought would help me spot interesting differences and came up with a
format inspired by the unified diff, with a twist. I wanted metrics to
be vertically aligned to easily see differences in orders of magnitude
and reduce the noise to a minimum.

The result is that taking this detour to script varnishstatdiff sped
my research up ultimately.

This should hopefully be portable to POSIX systems.

It needs testing at least on FreeBSD and SunOS...

### CODE REVIEW

**Comment by Dridi** [comment]
Rebased against master and updated to skip the test if `diff(1)` is missing (see f89e900fa2f35ec04605c3245e2ea48e43f721d9).

**Review by nigoroll — APPROVED** [review]
SunOS: `make check` in `contrib` passes

**Comment by nigoroll** [comment]
> SunOS: `make check` in `contrib` passes

as we just found out, only because it hits GNU awk first. It fails with `/usr/bin/awk`:

```
...
**   top   === shell {
**** top   shell_cmd|exec 2>&1 ; 
**** top   shell_cmd|\tvarnishstatdiff stat1.txt stat2.txt | tee diff.txt
**** dT    0.905
**** top   shell_out|C.utf-8: unknown locale
**** top   shell_out|--- stat1.txt
**** top   shell_out|+++ stat2.txt
**** top   shell_out| MAIN.cache_miss-0     -0.00             Cache misses
**** top   shell_out|    +1     +0.00
**** top   shell_out|-MAIN.client_req 0      0.00             Good client requests received
**** top   shell_out|+MAIN.esi_req 0      0.00             ESI subrequests
**** top   shell_out| MAIN.n_object-0      .                object structs made
**** top   shell_out|    +1      .
**** top   shell_status = 0x0000
**   top   === shell {
**** top   shell_cmd|exec 2>&1 ; 
**** top   shell_cmd|\tsed 's/@/ /' >expected.txt <<-EOF
**** top   shell_cmd|\t--- stat1.txt
**** top   shell_cmd|\t+++ stat2.txt
**** top   shell_cmd|\t@MAIN.cache_miss  -0  -0.00  Cache misses
**** top   shell_cmd|\t@                 +1  +0.00
**** top   shell_cmd|\t-MAIN.client_req   0   0.00  Good client requests received
**** top   shell_cmd|\t+MAIN.esi_req      0   0.00  ESI subrequests
**** top   shell_cmd|\t@MAIN.n_object    -0   .     object structs made
**** top   shell_cmd|\t@                 +1   .
**** top   shell_cmd|\tEOF
**** top   shell_cmd|
**** top   shell_cmd|\tdiff -u expected.txt diff.txt
**** dT    0.921
**** top   shell_out|--- expected.txt\t2022-08-29 15:18:55.195614453 +0200
**** top   shell_out|+++ diff.txt\t2022-08-29 15:18:55.183329044 +0200
**** top   shell_out|@@ -1,8 +1,8 @@
**** top   shell_out| --- stat1.txt
**** top   shell_out| +++ stat2.txt
**** top   shell_out|- MAIN.cache_miss  -0  -0.00  Cache misses
**** top   shell_out|-                  +1  +0.00
**** top   shell_out|--MAIN.client_req   0   0.00  Good client requests received
**** top   shell_out|-+MAIN.esi_req      0   0.00  ESI subrequests
**** top   shell_out|- MAIN.n_object    -0   .     object structs made
**** top   shell_out|-                  +1   .
**** top   shell_out|+ MAIN.cache_miss-0     -0.00             Cache misses
**** top   shell_out|+    +1     +0.00
**** top   shell_out|+-MAIN.client_req 0      0.00             Good client requests received
**** top   shell_out|++MAIN.esi_req 0      0.00             ESI subrequests
**** top   shell_out|+ MAIN.n_object-0      .                object structs made
**** top   shell_out|+    +1      .
**** top   shell_status = 0x0001
---- top   shell_exit not as expected: got 0x0001 wanted 0x0000
...
```

**Comment by Dridi** [comment]
It seems that the reason why it didn't work was because I was relying on unspecified behavior. I used a for loop over an array and the iteration is not guaranteed.

Tested on FreeBSD, @nigoroll please try again on SunOS.

**Comment by nigoroll** [comment]
3d331ab2961d1de1882f9a9b9aabe3ef54c4cec6 works with `/usr/bin/awk` on SunOS:

```
$ strings /usr/bin/awk | grep -E '^vers'
version Oct 11, 1989
```

**Review by nigoroll — APPROVED** [review]

**Pull request merged**
