### PR TITLE
release: Prep work before the next release

### PR DESCRIPTION
**Pull request by Dridi**
This is currently work in progress, but I plan to cover a first sweep of:

- [x] VSL (in)compatibility
- [x] initial release notes
- [x] initial upgrade notes
- [x] VRT history
- [x] libvarnishapi review
- [ ] gc SLTs?

### CODE REVIEW

**Comment by Dridi** [comment]
I'm afraid not, sorry. But we could maybe build packages with jemalloc support disabled for ARM? cc @hermunn

**Comment by jocel1** [comment]
That would definitely be great, I'm currently using the patch from 3881 to disable jemalloc on AWS ARM EC2 instances (both graviton 2 and graviton 3), and it has been working without any issue for 3 months now.

**Comment by hermunn** [comment]
> I'm afraid not, sorry. But we could maybe build packages with jemalloc support disabled for ARM? cc @hermunn

I think we should use slightly different words here, and simply decide that the default is building without `jemalloc` on ARM. If we do this, then we will ship packages without `jemalloc` wit an entry in the change log about the change. I would love to have more data, of course, but right now I think switching away from `jemalloc` on ARM is a natural choice.

**Comment by jocel1** [comment]
Hi @hermunn!
FYI I've added a few data about the behaviour on arm with and without jemalloc on https://github.com/varnishcache/varnish-cache/issues/3879

**Comment by Dridi** [comment]
For RPMs it could look like this:

```diff
--- redhat/varnish.spec
+++ redhat/varnish.spec
@@ -81,7 +81,11 @@ Varnish Cache is a high-performance HTTP accelerator
 
 
 %build
+%ifnarch aarch64
 %configure --localstatedir=/var/lib --with-contrib
+%else
+%configure --localstatedir=/var/lib --with-contrib --without-jemalloc
+%endif
 %make_build V=1
```

Not sure about other package managers.

**Comment by Dridi** [comment]
These rules are actually broken, we would do this instead:

```diff
--- debian/rules
+++ debian/rules
@@ -3,18 +3,18 @@
 DH_VERBOSE=1
 
 # List of architectures where jemalloc is not available
-DISABLE_JEMALLOC_ARCH_LIST := hppa m68k
+WITHOUT_JEMALLOC_ARCH_LIST := hppa m68k arm64
 
 # Explicitly initialize a variable to select architecture, unless it has been
-# defined before.  This is compared against the DISABLE_*_LIST variables later
+# defined before.  This is compared against the WITHOUT_*_LIST variables later
 # in this makefile
 DEB_HOST_ARCH ?= $(shell dpkg-architecture -qDEB_HOST_ARCH)
 
 # Set local state dir for FHS
 LOCAL_CONFIGURE_FLAGS  = --localstatedir=/var/lib --libdir=/usr/lib
 
-ifneq ($(filter $(DEB_HOST_ARCH),$(DISABLE_JEMALLOC_ARCH_LIST)),)
-LOCAL_CONFIGURE_FLAGS += --disable-jemalloc
+ifneq ($(filter $(DEB_HOST_ARCH),$(WITHOUT_JEMALLOC_ARCH_LIST)),)
+LOCAL_CONFIGURE_FLAGS += --without-jemalloc
 endif
 
 # Ship contrib scripts
```

**Comment by Dridi** [comment]
https://github.com/varnishcache/pkg-varnish-cache/pull/162

**Pull request merged**
