### PR TITLE
make the copyright section optional again

### PR DESCRIPTION
**Pull request by nigoroll**

### CODE REVIEW

**Comment by bsdphk** [comment]
Why is this a good idea ?

**Comment by nigoroll** [comment]
vmodtool accepted `$Module` as the first line in the past.
So was it intentional to make the first (copyright) section mandatory? If yes, I could prep a patch to emit a proper error message.

**Comment by nigoroll** [comment]
opinions on irc 

> (13:11:03) gquintar: slink: I don't care, but I would argue that it's not vmodtool's place to enforce such things, more so because it's a generic tool used for all vmods, not just the in-tree ones
> (13:14:17) fgs: +1

**Comment by lkarsten** [comment]
Backport review: this is a regression in master, not for 4.1.

**Pull request closed without merging**
