### PR TITLE
Only accept C identifiers as acls

### LINKED ISSUE #1883: IP matching with a header crashes the vcc
``server.ip ~ resp.http.foo`` crashe the vcl compilation

## Expected Behavior
Compilation error with error message explaining the behavior is invalid

## Current Behavior
Crash

## Steps to Reproduce (for bugs)
vtc:
```
varnishtest "Matching on an empty string"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_deliver {
		if (server.ip ~ resp.http.foo) {
			set resp.http.wont = "reach";
		}
	}
} -start

client c1 {
	txreq
	rxresp
} -run
```

## Your Environment
* Version used: master
* Operating System and version: arch linux, up-to-date at the time of writing

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #1883.

### CODE REVIEW

**Comment by bsdphk** [comment]
OK for commit.

**Comment by Dridi** [comment]
I believe this is the wrong fix, now that named ACLs have a proper type it is possible to get one from an expression involving a vmod.

**Comment by fgsch** [comment]
That would require more changes that are not specific to the problem at hand or this fix, aka this does not break anything that was working before.

**Comment by Dridi** [comment]
That's a proper fix for the 4.0 branch, but not for  4.1 or master. There should be a way to fail the compilation if the expression's value is not an ACL instead of asserting.

**Comment by fgsch** [comment]
Dridi, no idea what you are talking about. Did you check the code and or run it pre and post fix or you're assuming?

**Comment by Dridi** [comment]
I might, will check.

**Comment by lkarsten** [comment]
backports handled in #1883.

**Pull request closed without merging**
