### PR TITLE
mgt: Always recreate secret file on startup

### PR DESCRIPTION
**Pull request by scance**

### CODE REVIEW

**Comment by scance** [comment]
Failures seem to be caused by an ongoing github incident (https://www.githubstatus.com/) AFAICT.

**Comment by walid-git** [comment]
I think you also have a failing test: 
```
**   top   === shell -err -expect {Cannot create secret-file in} {
**** top   shell_cmd|exec 2>&1 ; 
**** top   shell_cmd|\tmkdir /tmp/vtc.97918.6a48ac11/is_a_dir /tmp/vtc.97918.6a48ac11/is_a_dir/_.secret
**** top   shell_cmd|\tvarnishd -n /tmp/vtc.97918.6a48ac11/is_a_dir -d -a :0
**** dT    1.014
**** top   shell_out|Error: Cannot remove pre-existing secret-file in /tmp/vtc.97918.6a48ac11/is_a_dir (Is a directory)
**** top   shell_out|(-? gives usage)
**** top   shell_status = 0x0002
---- top   shell_expect not found: ("Cannot create secret-file in")
*    top   RESETTING after ../../../../bin/varnishtest/tests/u00000.vtc
*    top   TEST ../../../../bin/varnishtest/tests/u00000.vtc FAILED
#    top  TEST ../../../../bin/varnishtest/tests/u00000.vtc FAILED (1.014) exit=2
FAIL tests/u00000.vtc (exit status: 2)
```

**Comment by scance** [comment]
Indeed I do... Will need to think of the relevance of that existing test.

**Review by nigoroll — APPROVED** [review]
👍🏽 on the basic concept, irrespective of the discussion about vtcs

**Comment by Dridi** [comment]
bugwash: ok

**Pull request merged**
