### PR TITLE
Backport too many VCLs

### PR DESCRIPTION
**Pull request by andrewwiik**
Commit List:

https://github.com/varnishcache/varnish-cache/commit/b51bc4a787709d340d6753aa02025837183371c0
https://github.com/varnishcache/varnish-cache/commit/5d8a6c0012c05c2f095c3a59e9f1dbc89b9f2c55
https://github.com/varnishcache/varnish-cache/commit/3c87f32a341ce14a28f34067c29ef428466f2a48
https://github.com/varnishcache/varnish-cache/commit/0bff7aab71d0e2710cecacde1f0f10a99bfe7e80
https://github.com/varnishcache/varnish-cache/commit/cf14a0fd774fcbcd4bfd2d50bcbe029f63ff7e0e
https://github.com/varnishcache/varnish-cache/commit/c22ccdcb2c605a78ecc07ffef694f3e0d5a34cc1
https://github.com/varnishcache/varnish-cache/commit/20c8aafb281ed5693771d65dc4e33e827173946c

### CODE REVIEW

**Comment by andrewwiik** [comment]
@rezan Can you review this

**Comment by rezan** [comment]
Yup, just going to run thru a few tests and confirm that this resolves the issue. Next week...

**Comment by rezan** [comment]
Original issue https://github.com/varnishcache/varnish-cache/issues/2713

**Comment by Dridi** [comment]
I'm planning to revert the following commit from this series:

> 795366627 Formally expose VSB_tofile in libvarnishapi

It shouldn't be needed for the feature at hand and if we need to it in the future it should be a separate back-port.

Additionally, it was back-ported in a way that diverges symbol versioning despite an identical soname between the 6.0 branch and other 6.x releases. (And conceptually it should have been picked last.)

I'll wait to see if you have a strong case for keeping this patch, just in case.

**Pull request merged**
