### PR TITLE
retire s_req - it is identical to client_req

### PR DESCRIPTION
**Pull request by nigoroll**
do we need any more words?

### CODE REVIEW

**Comment by bsdphk** [comment]
No objection.

Not sure if fallout in any important tools.

**Comment by nigoroll** [comment]
it should be easy change or alias in tools. Will add a changelog entry

**Comment by fgsch** [comment]
Applied.

**Comment by hermunn** [comment]
Backport review: We will not do this in 4.1, as it the gain of a back port is tiny compared to the potential problems this can cause.

**Pull request closed without merging**
