### PR TITLE
cannot link to varnishapi, symbols missing

### PR DESCRIPTION
**Pull request by dmatetelki**
fixes https://github.com/varnishcache/varnish-cache/issues/2313

### CODE REVIEW

**Comment by Dridi** [comment]
I don't think we should fix this by retroactively *changing* what's in the 1.0 ABI.

**Comment by dmatetelki** [comment]
I wonder if anyone ever used it, since it never worked.

**Comment by Dridi** [comment]
The pattern for API "symbols" seems to discard double underscores. For example `Lck` functions have a `__` in their names, but macros are provided with single `_` equivalents. We may not want to expose them as-is.

**Comment by mbgrydeland** [comment]
These two symbols aren't fully exposed. They are not part of the documented API, but the VSM_FOREACH macro is part of the documented API and it uses these two functions. So the pattern is similar to that of the Lck API, and keeping the double underscores is the right "message" to send regarding their semi-exposed nature.

I'll merge this PR as is.

**Pull request merged**
