### PR TITLE
PRIV_* for object methods and PRIV_TASK in vcl init

### PR DESCRIPTION
**Pull request by nigoroll**

### CODE REVIEW

**Comment by nigoroll** [comment]
rebased

**Comment by nigoroll** [comment]
rebased

**Comment by nigoroll** [comment]
The travis failure is unrelated to this pr, see #2065

**Comment by nigoroll** [comment]
rebased

**Comment by nigoroll** [comment]
rebased and updated:
* rename `vrt_ctx .init` to `.event`
* 8df88bcc240a1343cf22e992519d2659bea36458 centralize vrt_ctx management for events

**Comment by bsdphk** [comment]
I have done this a lot less intrusive way, and cleaned up some stuff along the way.

Please try out your VTC stuff, and yell if it doesn't work and commit it if it does.

**Comment by nigoroll** [comment]
not yet:
```
**** v1    0.2 CLI RX| vgc.c: In function \xe2\x80\x98VGC_function_vcl_init\xe2\x80\x99:\n
**** v1    0.2 CLI RX| vgc.c:1520:11: error: implicit declaration of function \xe2\x80\x98VGC_vmod_\xe2\x80\x99 [-Werror=implicit-function-declaration]\n
**** v1    0.2 CLI RX|            VRT_priv_task(ctx, &VGC_vmod_(null)),\n
**** v1    0.2 CLI RX|            ^\n
**** v1    0.2 CLI RX| vgc.c:1520:41: error: \xe2\x80\x98null\xe2\x80\x99 undeclared (first use in this function)\n
**** v1    0.2 CLI RX|            VRT_priv_task(ctx, &VGC_vmod_(null)),\n
**** v1    0.2 CLI RX|                                          ^\n
**** v1    0.2 CLI RX| vgc.c:1520:41: note: each undeclared identifier is reported only once for each function it appears in\n
**** v1    0.2 CLI RX| cc1: all warnings being treated as errors\n

```
smells like something like https://github.com/varnishcache/varnish-cache/pull/2061/commits/dd3d23eb7b7813b45c51fff2d0e56deae268bae3 was missing , but I need to have a better look

It could help to look at the vtcs I proposed

**Comment by nigoroll** [comment]
merged manually. attn all backporters - commits in git log (reverse) order
1f746aeacb3b0ad463e30b035727da93e1486349
a3ee09b8cba977bb71c4f776d757c0d49c170527
811c0c5493831b24ed971fec6a15180774922b41
6d4447cedee482cfb6cb2019bb982250100007e4
ef9e5fff328843529b7d065d573037a398550946

**Comment by hermunn** [comment]
Not a bugfix, no backport to 4.1

**Pull request closed without merging**
