### PR TITLE
Use CircleCI 'machine' executors with QEMU emulation to build packages for different architectures

### PR DESCRIPTION
**Pull request by martin-g**
This way CircleCI could be used to build, test and create multiarch packages.

Alpine Linux aarch64 packaging is currently commented out because it fails while installing the dependencies. Needs more debugging, but the issue must be in the base Docker image because the same Shell script works just fine on amd64.

Discussion at the mailing list: https://varnish-cache.org/lists/pipermail/varnish-dev/2020-March/009523.html

**Note**: This is the same PR as https://github.com/varnishcache/varnish-cache/pull/3263 but without the merge commits as [requested](https://github.com/varnishcache/varnish-cache/pull/3263#issuecomment-621695426) by @Dridi . I've cherry-picked all non-merge commits and applied them on top of latest _master_
For all previous discussions please check https://github.com/varnishcache/varnish-cache/pull/3263

### CODE REVIEW

**Comment by Dridi** [comment]
Thanks for doing the dirty work, you saved me some trouble since it was on my plate for today.

As much as I appreciate the effort, I still think this is not in shape to be merged. There are some back-n-forth changes in the 63 (!) commits that should be avoided. For example 22760ae4a974e6001eb7cc8d0171d2023f41b822 shouldn't be needed if your PR doesn't make that change in the first place.

I'll go over the commits and see what I can find or do.

**Comment by martin-g** [comment]
Thanks, @Dridi! Let me know if should do some more changes!

**Comment by Dridi** [comment]
Trivia: ce4d5361426ed1996f670198d438b9fa4fea2469 ended up as an empty commit.

**Comment by Dridi** [comment]
I'm tentatively reverting two patches just to see whether they still apply, I'm not getting a 404 for the incriminated URL in https://bugs.centos.org/view.php?id=15615.

**Comment by Dridi** [comment]
The ci build is still ongoing [1], but the el8 job passed so the vault repository issue is gone.

Don't mind the travisci failure, please don't get me started on github's user experience.

I'm not happy with the fact that a circleci build takes more than 1h. What is taking so long @gquintard?

[1] it finished while I was typing

**Comment by martin-g** [comment]
Most of the time is spent on the aarch64-*** `package` jobs.
We can move those to run on a schedule (nightly or weekly) instead of on each commit.

**Comment by Dridi** [comment]
@martin-g please do that. Make sure to update your local branch with my changes first.

**Comment by martin-g** [comment]
I've moved the package jobs to run at 4 AM.
According to https://circleci.com/docs/2.0/faq/#can-workflows-be-scheduled-to-run-at-a-specific-time-of-day it should use UTC time but I've tried with 17:40 (11 minutes ago) and I didn't see `nightly` workflow at https://app.circleci.com/pipelines/github/martin-g/varnish-cache.
I will check again tomorrow morning to see whether the one at 4 AM has been executed.

**Comment by Dridi** [comment]
@martin-g this looks promising, I will have a look tomorrow (I'm way way past office hours in my time zone).

Can you also update the circleci readme to reflect that change in the mean time?

**Comment by martin-g** [comment]
Unfortunately there is no build at 4AM for `master` branch at https://app.circleci.com/pipelines/github/martin-g/varnish-cache.
I will investigate it!

And I will update the README!

**Comment by martin-g** [comment]
I've updated the README!

The scheduled workflows run only if the CircleCI config applies to the filtered (via `filters`) branch. I.e. the nightly build for `master` branch will start as soon as this PR is merged into master.

**Comment by Dridi** [comment]
I updated the README, and I'm going to disregard any other peeve I have if we agree on a3a52a47d3a8f4c4da18cab783407b2381b6b952.

**Comment by martin-g** [comment]
The README looks much better now! Thank you, @Dridi !

**Comment by Dridi** [comment]
I just opened #3320 and it doesn't look like CircleCI kicked in for the pull request, unlike what the README says :)

**Comment by martin-g** [comment]
That means "Build forked pull requests" is not enabled for Varnish in CircleCI.
You should go to https://app.circleci.com/pipelines/github/varnishcache/varnish-cache, then at the top-right corner click on "Project Settings" > menu on the left "Advance" > enable "Build forked pull requests"

**Comment by Dridi** [comment]
Thanks for the tip!

**Comment by gquintard** [comment]
I've activated it

**Pull request closed without merging**
